### ISSUE TITLE
CUDA Driver and CUDA runtime version mismatch after update

### ISSUE THREAD

**Issue by IWriteThings** [davisking/dlib#1029]
## Expected Behavior
Application was working. Application now fails with error. Everything worked great previously. My driver and card appear functional as I can build the test nvidia projects, it passes dlib build, and I can also use hashcat with my GPU for password cracking just fine. The error appears to be in the gpu_data.cpp code.

## Current Behavior

```
Traceback (most recent call last):
  File "./example.py", line 2, in <module>
    from ml_face import *
  File "/home/aaron/Development/bulk-image-facial-recognition/ml_face.py", line 1, in <module>
    import face_recognition
  File "/usr/lib/python3.6/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/usr/lib/python3.6/site-packages/face_recognition/api.py", line 21, in <module>
    cnn_face_detector = dlib.cnn_face_detection_model_v1(cnn_face_detection_model)
RuntimeError: Error while calling cudaGetDevice(&the_device_id) in file /home/aaron/Development/tmp/dlib/dlib/dnn/gpu_data.cpp:178. code: 35, reason: CUDA driver version is insufficient for CUDA runtime version
```

The line in question is -

```
                CHECK_CUDA(cudaGetDevice(&the_device_id));

```

## Steps to Reproduce

1. Update to latest drivers for nvidia provided by manjaro

2. Attempt to run application

3. Receive error.

```
 nvidia-smi                                                                                                                   1 < 06:39:20
Mon Dec 25 06:40:53 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.98                 Driver Version: 384.98                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GPU         Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   43C    P8    N/A /  N/A |     11MiB /  1998MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       345      G   /usr/lib/xorg-server/Xorg                      8MiB |
+-----------------------------------------------------------------------------+

```
* **Version**: Latest 19.8.99
* **Where did you get dlib**: GitHub
* **Platform**: 
```
lsb_release -a                                                                                                             127 < 06:42:23
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	17.1-rc2
Codename:	Hakoila
```

* **Compiler**: gcc-6

**Comment by davisking** [comment]
Did you recompile dlib against the new cuda toolkit after installing the new cuda toolkit?

**Comment by IWriteThings** [comment]
Affirmative. I performed a completely fresh build of dlib.

**Comment by IWriteThings** [comment]
```
export CC=/usr/bin/gcc-6; cmake .. -DUSE_AVX_INSTRUCTIONS=1; cmake --build .;
python3 setup.py install --yes USE_AVX_INSTRUCTIONS
```

Those are the two commands I ran.

**Comment by davisking** [comment]
Don't do all that stuff.  Just `python3 setup.py install --yes USE_AVX_INSTRUCTIONS`.   There is all this nonsense on the internet about building dlib before running setup.py, you don't need to do that.  

Anyway, this isn't a bug in dlib.  There is something wrong with your cuda runtime install.  I would try reinstalling cuda.
