### ISSUE TITLE
python setup.py install --compiler-flags "-mfpu=neon" gives error

### ISSUE THREAD

**Issue by kmonachopoulos** [davisking/dlib#1074]
Hello,

I am trying to build dlib on my Hikeyboard. I followed the instructions as they are described : 

In dlib/examples : 

```
mkdir build; 
cd build; cmake .. ; 
cmake --build .
```

All went well, but when I run `python setup.py install --compiler-flags "-mfpu=neon"
`
 I get the following error : 

```
running install
running bdist_egg
running egg_info
writing dlib.egg-info/PKG-INFO
writing top-level names to dlib.egg-info/top_level.txt
writing dependency_links to dlib.egg-info/dependency_links.txt
package init file 'dlib/__init__.py' not found (or not a regular file)
reading manifest file 'dlib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dlib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-aarch64/egg
running install_lib
running build_py
running build_ext
Invoking CMake setup: '['cmake', '/hdd/konmon01/dlib_original/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/hdd/konmon01/dlib_original/dlib/build/lib.linux-aarch64-2.7', '-DPYTHON_EXECUTABLE=/usr/bin/python', '-DCMAKE_CXX_FLAGS=-mfpu=neon', '-DCMAKE_BUILD_TYPE=Release']'
-- The CXX compiler identification is unknown
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- broken
CMake Error at /usr/share/cmake-3.7/Modules/CMakeTestCXXCompiler.cmake:44 (message):
  The C++ compiler "/usr/bin/c++" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: /hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeTmp



  Run Build Command:"/usr/bin/make" "cmTC_91b6c/fast"

  /usr/bin/make -f CMakeFiles/cmTC_91b6c.dir/build.make
  CMakeFiles/cmTC_91b6c.dir/build

  make[1]: Entering directory
  '/hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeTmp'


  Building CXX object CMakeFiles/cmTC_91b6c.dir/testCXXCompiler.cxx.o

  /usr/bin/c++ -mfpu=neon -o CMakeFiles/cmTC_91b6c.dir/testCXXCompiler.cxx.o
  -c
  /hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeTmp/testCXXCompiler.cxx


  c++: error: unrecognized command line option ‘-mfpu=neon’

  CMakeFiles/cmTC_91b6c.dir/build.make:65: recipe for target
  'CMakeFiles/cmTC_91b6c.dir/testCXXCompiler.cxx.o' failed

  make[1]: *** [CMakeFiles/cmTC_91b6c.dir/testCXXCompiler.cxx.o] Error 1

  make[1]: Leaving directory
  '/hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeTmp'


  Makefile:126: recipe for target 'cmTC_91b6c/fast' failed

  make: *** [cmTC_91b6c/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt


-- Configuring incomplete, errors occurred!
See also "/hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeOutput.log".
See also "/hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 231, in <module>
    'Topic :: Software Development',
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 170, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 156, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 119, in run
    self.build_extension(ext)
  File "setup.py", line 150, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=build_folder)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/hdd/konmon01/dlib_original/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/hdd/konmon01/dlib_original/dlib/build/lib.linux-aarch64-2.7', '-DPYTHON_EXECUTABLE=/usr/bin/python', '-DCMAKE_CXX_FLAGS=-mfpu=neon', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
```
PS : I got the same error even withought using the neon flag .. 

Any idea what that is ?

**Comment by davisking** [comment]
Read the error.  It says right in it `c++: error: unrecognized command line option ‘-mfpu=neon’`

**Comment by kmonachopoulos** [comment]
I saw that, but I got the same error even if I don't pass any flags to the compiler. What dhould I change??

**Comment by davisking** [comment]
Run `python setup.py build` and paste the output here.

As an aside, you don't need to compile the C++ example programs to use
python.  They are totally unrelated.  So whatever instructions you were
following weren't dlib's instructions and are wrong.  You should be
referring to the official documentation on dlib.net instead.

**Comment by kmonachopoulos** [comment]
I understand that examples are unrelated. This is the output when I use the command `python setup.py build`. 

```

  make[1]: *** [CMakeFiles/cmTC_5c733.dir/testCXXCompiler.cxx.o] Error 1

  make[1]: Leaving directory
  '/hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeTmp'


  Makefile:126: recipe for target 'cmTC_5c733/fast' failed

  make: *** [cmTC_5c733/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt


-- Configuring incomplete, errors occurred!
See also "/hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeOutput.log".
See also "/hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 231, in <module>
    'Topic :: Software Development',
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 119, in run
    self.build_extension(ext)
  File "setup.py", line 150, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=build_folder)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/hdd/konmon01/dlib_original/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/hdd/konmon01/dlib_original/dlib/build/lib.linux-aarch64-2.7', '-DPYTHON_EXECUTABLE=/usr/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
root@johgro01_hikey960:/hdd/konmon01/dlib_original/dlib# ls
build  CMakeLists.txt  dlib  dlib.egg-info  docs  examples  ISSUE_TEMPLATE.md  MANIFEST.in  python_examples  README.md	setup.py  tools
root@johgro01_hikey960:/hdd/konmon01/dlib_original/dlib# clear
root@johgro01_hikey960:/hdd/konmon01/dlib_original/dlib# python setup.py build
running build
running build_py
package init file 'dlib/__init__.py' not found (or not a regular file)
running build_ext
Invoking CMake setup: '['cmake', '/hdd/konmon01/dlib_original/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/hdd/konmon01/dlib_original/dlib/build/lib.linux-aarch64-2.7', '-DPYTHON_EXECUTABLE=/usr/bin/python', '-DCMAKE_BUILD_TYPE=Release']'
-- The CXX compiler identification is unknown
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- broken
CMake Error at /usr/share/cmake-3.7/Modules/CMakeTestCXXCompiler.cmake:44 (message):
  The C++ compiler "/usr/bin/c++" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: /hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeTmp



  Run Build Command:"/usr/bin/make" "cmTC_61bc8/fast"

  /usr/bin/make -f CMakeFiles/cmTC_61bc8.dir/build.make
  CMakeFiles/cmTC_61bc8.dir/build

  make[1]: Entering directory
  '/hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeTmp'


  Building CXX object CMakeFiles/cmTC_61bc8.dir/testCXXCompiler.cxx.o

  /usr/bin/c++ -mfpu=neon -o CMakeFiles/cmTC_61bc8.dir/testCXXCompiler.cxx.o
  -c
  /hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeTmp/testCXXCompiler.cxx


  c++: error: unrecognized command line option ‘-mfpu=neon’

  CMakeFiles/cmTC_61bc8.dir/build.make:65: recipe for target
  'CMakeFiles/cmTC_61bc8.dir/testCXXCompiler.cxx.o' failed

  make[1]: *** [CMakeFiles/cmTC_61bc8.dir/testCXXCompiler.cxx.o] Error 1

  make[1]: Leaving directory
  '/hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeTmp'


  Makefile:126: recipe for target 'cmTC_61bc8/fast' failed

  make: *** [cmTC_61bc8/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt


-- Configuring incomplete, errors occurred!
See also "/hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeOutput.log".
See also "/hdd/konmon01/dlib_original/dlib/build/temp.linux-aarch64-2.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 231, in <module>
    'Topic :: Software Development',
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 119, in run
    self.build_extension(ext)
  File "setup.py", line 150, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=build_folder)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/hdd/konmon01/dlib_original/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/hdd/konmon01/dlib_original/dlib/build/lib.linux-aarch64-2.7', '-DPYTHON_EXECUTABLE=/usr/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
```

So building the python bindings will build the c++ backend as well ?

**Comment by kmonachopoulos** [comment]
I can confirm that withought the compiler flags it builds and works perfectly. I must figure out what happens when the compiler flag `--compiler-flags "-mfpu=neon"` is set ...

**Comment by kmonachopoulos** [comment]
Since I am using ArmV8 there is no need to set neon flags to the compiler like ArmV7. Whenever neon code is tracked, the implementation is taking place to NEON engine. Thanks.

**Comment by axmadjon** [comment]
@kmonachopoulos  
I also had a similar error
the error disappeared after installing python-dev

**Comment by kmonachopoulos** [comment]
@Axmadjon Arm v8 has Neon backend by default. There is no need to push neon
flags to the compiler to generate vectorized binaries. That was the error.
