### ISSUE TITLE
CMake Error: Could NOT find Threads (missing: Threads_FOUND)

### ISSUE THREAD

**Issue by trnet4334** [davisking/dlib#1084]
## Expected Behavior
Install dlib successfully under virtual environment.

## Current Behavior
Activate virtualenv, and use `pip install dlib`.

Error message as below:
```
Collecting dlib
  Using cached dlib-19.9.0.tar.gz
Building wheels for collected packages: dlib
  Running setup.py bdist_wheel for dlib ... error
  Complete output from command /Users/hornet/.virtualenvs/facepy3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/pip-build-3n7ncr_5/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/tmp7cskql_qpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib/__init__.py' not found (or not a regular file)
  running build_ext
  Invoking CMake setup: 'cmake /private/var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/pip-build-3n7ncr_5/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/pip-build-3n7ncr_5/dlib/build/lib.macosx-10.13-x86_64-3.6 -DPYTHON_EXECUTABLE=/Users/hornet/.virtualenvs/facepy3/bin/python3.6 -DCMAKE_BUILD_TYPE=Release'
  -- The C compiler identification is AppleClang 9.0.0.9000039
  -- The CXX compiler identification is AppleClang 9.0.0.9000039
  -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
  -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
  -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /Users/hornet/.virtualenvs/facepy3/bin/python3.6 (found version "3.6.4")
  -- Found PythonLibs: /usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
  -- Performing Test HAS_CPP14_FLAG
  -- Performing Test HAS_CPP14_FLAG - Success
  -- pybind11 v2.3.dev0
  -- Enabling SSE4 instructions
  -- Looking for pthread.h
  -- Looking for pthread.h - not found
  CMake Error at /Applications/CMake.app/Contents/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
    Could NOT find Threads (missing: Threads_FOUND)
  Call Stack (most recent call first):
    /Applications/CMake.app/Contents/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
    /Applications/CMake.app/Contents/share/cmake-3.10/Modules/FindThreads.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    /private/var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/pip-build-3n7ncr_5/dlib/dlib/CMakeLists.txt:239 (find_package)

 -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/pip-build-3n7ncr_5/dlib/build/temp.macosx-10.13-x86_64-3.6/CMakeFiles/CMakeOutput.log".
  See also "/private/var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/pip-build-3n7ncr_5/dlib/build/temp.macosx-10.13-x86_64-3.6/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/pip-build-3n7ncr_5/dlib/setup.py", line 238, in <module>
      'Topic :: Software Development',
    File "/Users/hornet/.virtualenvs/facepy3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/hornet/.virtualenvs/facepy3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/pip-build-3n7ncr_5/dlib/setup.py", line 119, in run
      self.build_extension(ext)
    File "/private/var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/pip-build-3n7ncr_5/dlib/setup.py", line 153, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/pip-build-3n7ncr_5/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/pip-build-3n7ncr_5/dlib/build/lib.macosx-10.13-x86_64-3.6', '-DPYTHON_EXECUTABLE=/Users/hornet/.virtualenvs/facepy3/bin/python3.6', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

```
----------------------------------------
`Command "/Users/hornet/.virtualenvs/facepy3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/pip-build-3n7ncr_5/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/pip-m6qyjpki-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/hornet/.virtualenvs/facepy3/bin/../include/site/python3.6/dlib" failed with error code 1 in /private/var/folders/82/9l5bg5052ls53n07xmgbnrrr0000gq/T/pip-build-3n7ncr_5/dlib/`

## Steps to Reproduce

* **Version**:  19.9
* **Where did you get dlib**: This repo.
* **Platform**: macOS High Sierra Version 10.13.2
* **Compiler**: Xcode Version 9.2

I tried to reinstall boost, compiler and rebuild virtual environment, but the issue still exist.

**Comment by davisking** [comment]
Boost is not required. 

Something is wrong with your XCode install since it's missing threads.  You should reinstall xcode, or update to the newest.  Although any version should support threading.  But in any case, this isn't a dlib error.  You need to have a working compiler installed on your computer.

**Comment by zmuhsin** [comment]
I also have this error when try to install dlib on linux:
"package init file 'dlib/__init__.py' not found (or not a regular file)
running build_ext
error: [Errno 38] Function not implemented"
Could you please tell me how to fix it.
Thanks.

**Comment by davisking** [comment]
@zmuhsin fill out the issue template.

**Comment by zmuhsin** [comment]
Thank you.
