### ISSUE TITLE
Using pip install dlib fails on windows

### ISSUE THREAD

**Issue by ZusorCode** [davisking/dlib#1267]
## Expected Behavior
Trying to install dlib with python bindings  using ´pip install dlib´

## Current Behavior
```
pip install dlib
Collecting dlib
  Using cached https://files.pythonhosted.org/packages/54/ff/5781a11bdc0d1c90a813f3f66d460abf628e5114856a842d18d43f709a7a/dlib-19.10.0.tar.gz
Installing collected packages: dlib
  Running setup.py install for dlib ... error
Exception:
Traceback (most recent call last):
  File "c:\users\tobias\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 50: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\tobias\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\tobias\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\tobias\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\tobias\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\tobias\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\tobias\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 50: invalid start byte
```
## Steps to Reproduce

Open cmd and as normal user or admin and run `pip install dlib`

* **Version**: 19.10.0
* **Where did you get dlib**: PyPI
* **Platform**: Windows 10 Home, 64 bit
* **Compiler**: Not sure but I think mingw

**Comment by davisking** [comment]
dlib's unit tests run all these versions of python on windows, including the 32bit python 3.6.  See: https://ci.appveyor.com/project/davisking/dlib-1mqn9 for the latest run where all the builds and tests pass. You must be doing something unusual that you aren't reporting.

**Comment by elbaro** [comment]
Try pip10:
https://github.com/pypa/pip/issues/4863

**Comment by magicshuang** [comment]
update pip

**Comment by ZusorCode** [comment]
Updating pip fixed it
