### ISSUE TITLE
UnicodeDecodeError when compiling (ascii codec can't encode...)

### ISSUE THREAD

**Issue by AbdealiJK** [davisking/dlib#127]
I got a UnicodeDecodeError when compiling dlib. It seems to be happening when the log messages are being printed. Possibly one of the log messages contains a character that ascii can't handle ?

Here is the build where the whole error can be seen: https://travis-ci.org/AbdealiJK/file-metadata/builds/135357260 Line 583

The traceback is:
```
    [ 71%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_png.o
    [ 73%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/jpeg_loader.o
    [ 74%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_jpeg.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cKjSMK/dlib/setup.py", line 587, in <module>
        'Topic :: Software Development',
      File "/home/travis/miniconda/envs/py2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/travis/miniconda/envs/py2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/travis/miniconda/envs/py2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/travis/miniconda/envs/py2.7/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/travis/miniconda/envs/py2.7/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/home/travis/miniconda/envs/py2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/travis/miniconda/envs/py2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-cKjSMK/dlib/setup.py", line 394, in run
        self.build_dlib()
      File "/tmp/pip-build-cKjSMK/dlib/setup.py", line 509, in build_dlib
        if run_process(cmake_cmd):
      File "/tmp/pip-build-cKjSMK/dlib/setup.py", line 297, in run_process
        _log_buf(buf)
      File "/tmp/pip-build-cKjSMK/dlib/setup.py", line 269, in _log_buf
        log.info(line)
      File "/home/travis/miniconda/envs/py2.7/lib/python2.7/distutils/log.py", line 40, in info
        self._log(INFO, msg, args)
      File "/home/travis/miniconda/envs/py2.7/lib/python2.7/distutils/log.py", line 30, in _log
        stream.write('%s\n' % msg)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 71-73: ordinal not in range(128)
```

**Comment by AbdealiJK** [comment]
On further analysis, I found that dlib is already using `sys.stdout.encoding` to decode the log messages, so i'm not sure why this is being caused.
I checked the `sys.stdout.encoding` on Travis, and it does seem to be UTF-8.
Not sure what the issue could be. Could this be a bug in conda or distutils ?

**Comment by davisking** [comment]
I don't get any errors on any of the systems I have access to, so I can't
say.  What system is this on? If there is some work around you can submit a
pull request :)

**Comment by AbdealiJK** [comment]
It's happening on Travis, I'm not getting it locally on any system.

A dirty workaround would be to check for travis using `os.environ.get('TRAVIS', 'false') == 'true'` and force it to decode the logs to ascii, but that's not nice.

I don't mind submitting the pull request, but I'm not sure of a good workaround :(

**Comment by AbdealiJK** [comment]
CC @jayvdb , is travis possibly doing some magic with the encoding ? Any clue about this ?

**Comment by davisking** [comment]
Yeah, don't avoid it like that :)

**Comment by jayvdb** [comment]
in `.travis.yml` , try adding `export PYTHONIOENCODING=UTF-8` .  If that works, something is opening subprocesses of python that have a default ascii stdout

**Comment by AbdealiJK** [comment]
Interesting, so doing that made it kind of work - [Travis build Line 687](https://travis-ci.org/AbdealiJK/file-metadata/builds/135429131#L687)
Looks like it now shows `â` instead of quotes - atleast it doesn't fail with the UnicodeDecodeError ^_^
When searching for the error online I found it referenced in [lammps](https://sourceforge.net/p/lammps/mailman/message/32775346/) and the actual characters should have been ‘’.

**Comment by AbdealiJK** [comment]
@jayvdb is this a travis issue or a dlib issue ? Can this issue be closed ?

**Comment by jayvdb** [comment]
It isnt travis.
We need to find which module is creating the subprocess.

**Comment by AbdealiJK** [comment]
Apparently the version of dlib on pypi (18.17.100) does not have the lines:
```
    if sys.stdout.encoding:
        buf = buf.decode(sys.stdout.encoding)
```
Which are there in the master's setup.py.
When I installed dlib from git (with pip on travis), it worked fine.

As it's already fixed on master, I'm closing this.
