### ISSUE TITLE
Dlib installation problem

### ISSUE THREAD

**Issue by dvigneshwer** [davisking/dlib#131]
I have followed all the steps correctly. PFB the error log,

```

<ipython-input-1-82a137582d6f> in <module>()
----> 1 import dlib

/usr/local/lib/python2.7/dist-packages/dlib-18.18.99-py2.7-linux-x86_64.egg/dlib/__init__.py in <module>()
----> 1 from .dlib import *
      2 __version__ = "18.18.99"

ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

```

**Comment by davisking** [comment]
How did you install openblas?  It's obviously not installed correctly on
your machine.

**Comment by dvigneshwer** [comment]
I installed using **sudo apt-get install libopenblas-dev**, after you had mentioned  and now have got a new error.
```
ImportError                               Traceback (most recent call last)
<ipython-input-1-82a137582d6f> in <module>()
----> 1 import dlib

/usr/local/lib/python2.7/dist-packages/dlib-18.18.99-py2.7-linux-x86_64.egg/dlib/__init__.py in <module>()
----> 1 from .dlib import *
      2 __version__ = "18.18.99"

ImportError: /usr/local/lib/python2.7/dist-packages/dlib-18.18.99-py2.7-linux-x86_64.egg/dlib/dlib.so: undefined symbol: dormqr_

```

**Comment by davisking** [comment]
Did you recompile dlib after installing openblas?

**Comment by ncbonde** [comment]
### i have got this error ...how to solve it??
` import face_recognition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, face_landmarks, face_encodings, compare_faces
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/api.py", line 21, in <module>
    face_encoder = dlib.face_recognition_model_v1(face_recognition_model)
AttributeError: 'module' object has no attribute 'face_recognition_model_v1'
`
