### ISSUE TITLE
png_loader failure on Windows

### ISSUE THREAD

**Issue by MaxBareiss** [davisking/dlib#1380]
## Expected Behavior

I am trying to train a shape predictor, following from [the python example](http://dlib.net/train_shape_predictor.py.html).

## Current Behavior

The code fails with the following stack trace on Windows:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 111, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\debugger.py", line 36, in debug
    run(address, filename, *args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\_main.py", line 47, in run_file
    run(argv, addr, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\_main.py", line 98, in _run
    _pydevd.main()
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\pydevd\pydevd.py", line 1628, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\pydevd\pydevd.py", line 1035, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\pydevd\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "My file name", line 19, in <module>
    dlib.train_shape_predictor(training_xml_path, "predictor.dat", options)
RuntimeError: png_loader: parse error in file imgs/00001.png
```
There's a lot of Visual Studio stuff in that stack trace, but if I run it without the debugger no stack trace is emitted. When I run the code in Linux it works correctly. When I debug with native code debugging turned on it fails on [png_loader.cpp:182](https://github.com/davisking/dlib/blob/master/dlib/image_loader/png_loader.cpp#L182).

When I view the XML file in `imglab`, it has no problems.

I have attached a project that reproduces the bug.
[dlib-bug.zip](https://github.com/davisking/dlib/files/2138706/dlib-bug.zip)

## Steps to Reproduce

* **Version**: 

Git master commit 6b581d91f

* **Where did you get dlib**: 

Git

* **Platform**: 

64 bit Windows 10 Build 1803 Anaconda Python 3.6.4
Ubuntu 16.04 Python 3.5.2 (From apt-get)

* **Compiler**: 

Visual Studio 2015 Compiled x64 Debug and Release
Ubuntu: `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609`

**Comment by davisking** [comment]
Thanks for the nice bug report.  I was able to reproduce this and it's because it's linking to the copy of libpng in anaconda, which is apparently broken or in some way incompatible with visual studio.  In any case, I've blacklisted the libpng in anaconda so dlib will never link to it. If you pull the latest code and reinstall it should work fine now.
