### ISSUE TITLE
Using without an X server

### ISSUE THREAD

**Issue by bamos** [davisking/dlib#15]
Hi, I'd like to use dlib to batch process images on a server with X.
Is there a flag I can set to enable this?

The first error I get is from matplotlib/pyplot:

```
(naive-dlib-frontalization.py:28314): Gdk-CRITICAL **: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "./scripts/naive-dlib-frontalization.py", line 19, in <module>
    from skimage import io
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/__init__.py", line 15, in <module>
    reset_plugins()
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 89, in reset_plugins
    _load_preferred_plugins()
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 69, in _load_preferred_plugins
    _set_plugin(p_type, preferred_plugins['all'])
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 81, in _set_plugin
    use_plugin(plugin, kind=plugin_type)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 251, in use_plugin
    _load(name)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 295, in _load
    fromlist=[modname])
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_plugins/matplotlib_plugin.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 109, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 11, in <module>
    from . import backend_gtk3
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk3.py", line 55, in <module>
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL
```

I can get around this error with the following imports before importing dlib:

```
import matplotlib as mpl
mpl.use('Agg')
```

Next, I get the following error, which I'm not yet sure how to resolve.

```
 1029 FATAL [1] dlib.gui_core: Unable to connect to the X display.
RuntimeError: Failed to initialize X11 resources
```

**Comment by bamos** [comment]
My current workaround is to use Xvfb:

```
$ Xvfb :1 & disown
$ export DISPLAY=:1
```

**Comment by davisking** [comment]
Are you trying to pop up a window or call some GUI function?

**Comment by bamos** [comment]
Sorry, and thanks @davisking - I had a `dlib.image_window()` hidden in my code!
It's working well with an X server now. :-)

Great code btw!
