### ISSUE TITLE
Import error in Python3, Fedora24, dlib18.18

### ISSUE THREAD

**Issue by jinyu121** [davisking/dlib#150]
Hi,

I installed dlib on fedora using `sudo dnf install python3-dlib`, no errors. but when I use it, errors occured.(python3-dlib.x86_64 18.18-3.fc24)

```
$ python3
Python 3.5.1 (default, Jun 20 2016, 14:48:22) 
[GCC 6.1.1 20160510 (Red Hat 6.1.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.5/site-packages/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: /usr/lib64/python3.5/site-packages/dlib/dlib.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE
```

And I have another try: `sudo pip3 install dlib`. 
I'm sure I have installed `boost`(boost-1.60.0-5.fc24.x86_64),`boost-devel`(boost-devel-1.60.0-5.fc24.x86_64),`boost-python3-devel`(boost-python3-devel-1.60.0-5.fc24.x86_64) and `boost-python3`(boost-devel-1.60.0-5.fc24.x86_64), but it told me something can't be found:

```
$ sudo pip install dlib
Collecting dlib
  Using cached dlib-18.17.100.zip      [[[[[[Do you notice that this version is 18.17, but dnf installed 18.18?]]]]]]
Installing collected packages: dlib
  Running setup.py install for dlib ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-he92a4d6/dlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-k5p5txv7-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Detected Python architecture: 64bit
    Configuring cmake ...
    -- The C compiler identification is GNU 6.1.1
    -- The CXX compiler identification is GNU 6.1.1
    -- Check for working C compiler: /bin/cc
    -- Check for working C compiler: /bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /bin/c++
    -- Check for working CXX compiler: /bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Could NOT find Boost
    -- Boost version: 1.60.0
    -- Found the following Boost libraries:
    --   python
    CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
      Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
      (Required is at least version "3.4")
    Call Stack (most recent call first):
      /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
      /usr/share/cmake/Modules/FindPythonLibs.cmake:265 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      /tmp/pip-build-he92a4d6/dlib/dlib/add_python_module:64 (FIND_PACKAGE)
      CMakeLists.txt:5 (include)
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-build-he92a4d6/dlib/tools/python/build/CMakeFiles/CMakeOutput.log".
    error: cmake configuration failed!
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-he92a4d6/dlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-k5p5txv7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-he92a4d6/dlib/
```

Do you have any suggestions to fix problem one?

THX

**Comment by davisking** [comment]
Many users have this problem.  It's because you have multiple versions of python and/or boost installed and are mixing them up.  You need to compile both boost.python and dlib for the version of python you will be using.  That fixes this problem.
