### ISSUE TITLE
Can dlib setup with pypy ？

### ISSUE THREAD

**Issue by blacksun1977** [davisking/dlib#1543]
In my project, I use pypy as the runtime of Python.
When I install Dlib to pypy, the following compilation anomalies occur.
```

[root@873734fc864b dlib-master]# pypy setup.py install
running install
running bdist_egg
running egg_info
writing dlib.egg-info/PKG-INFO
writing dependency_links to dlib.egg-info/dependency_links.txt
writing top-level names to dlib.egg-info/top_level.txt
package init file 'dlib/__init__.py' not found (or not a regular file)
reading manifest file 'dlib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dlib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Building extension for Python 2.7.13 (ab0b9caf307db6592905a80b8faffd69b39005b8, May 03 2018, 01:56:42)
Invoking CMake setup: 'cmake /root/dlib-master/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/root/dlib-master/build/lib.linux-x86_64-2.7 -DPYTHON_EXECUTABLE=/bin/pypy -DCMAKE_BUILD_TYPE=Release'
-- The C compiler identification is GNU 7.1.0
-- The CXX compiler identification is GNU 7.1.0
-- Check for working C compiler: /opt/devtools-7.1/bin/cc
-- Check for working C compiler: /opt/devtools-7.1/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/devtools-7.1/bin/c++
-- Check for working CXX compiler: /opt/devtools-7.1/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /bin/pypy (found version "2.7.13") 
-- Found PythonLibs: python2.7
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.2.2
-- Using CMake version: 3.13.0-rc3
-- Compiling dlib version: 19.16.99
-- SSE4 instructions can be executed by the host processor.
-- AVX instructions can be executed by the host processor.
-- Enabling AVX instructions
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for XOpenDisplay in /usr/lib64/libX11.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib64/libX11.so
-- Looking for jpeg_read_header
-- Looking for jpeg_read_header - found
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.23") 
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for module 'lapack'
--   No package 'lapack' found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found OpenBLAS library
-- Looking for sgetrf_single
-- Looking for sgetrf_single - found
-- Using OpenBLAS's built in LAPACK
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Looking for sgesv
-- Looking for sgesv - not found
-- Looking for sgesv_
-- Looking for sgesv_ - not found
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: /root/dlib-master/build/temp.linux-x86_64-2.7
Invoking CMake build: 'cmake --build . --config Release -- -j3'
Scanning dependencies of target dlib
[  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o
.
.
.
[ 75%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_jpeg.cpp.o
[ 76%] Linking CXX static library libdlib.a
[ 76%] Built target dlib
Scanning dependencies of target dlib_python
[ 77%] Building CXX object CMakeFiles/dlib_python.dir/src/dlib.cpp.o
[ 78%] Building CXX object CMakeFiles/dlib_python.dir/src/matrix.cpp.o
[ 79%] Building CXX object CMakeFiles/dlib_python.dir/src/vector.cpp.o
[ 80%] Building CXX object CMakeFiles/dlib_python.dir/src/svm_c_trainer.cpp.o
[ 81%] Building CXX object CMakeFiles/dlib_python.dir/src/svm_rank_trainer.cpp.o
[ 81%] Building CXX object CMakeFiles/dlib_python.dir/src/decision_functions.cpp.o
[ 82%] Building CXX object CMakeFiles/dlib_python.dir/src/other.cpp.o
[ 83%] Building CXX object CMakeFiles/dlib_python.dir/src/basic.cpp.o
[ 84%] Building CXX object CMakeFiles/dlib_python.dir/src/cca.cpp.o
[ 85%] Building CXX object CMakeFiles/dlib_python.dir/src/sequence_segmenter.cpp.o
[ 86%] Building CXX object CMakeFiles/dlib_python.dir/src/svm_struct.cpp.o
[ 87%] Building CXX object CMakeFiles/dlib_python.dir/src/image.cpp.o
[ 87%] Building CXX object CMakeFiles/dlib_python.dir/src/image2.cpp.o
[ 88%] Building CXX object CMakeFiles/dlib_python.dir/src/image3.cpp.o
[ 89%] Building CXX object CMakeFiles/dlib_python.dir/src/image4.cpp.o
[ 90%] Building CXX object CMakeFiles/dlib_python.dir/src/rectangles.cpp.o
[ 91%] Building CXX object CMakeFiles/dlib_python.dir/src/object_detection.cpp.o
/root/dlib-master/tools/python/src/object_detection.cpp: In function ‘std::shared_ptr<dlib::simple_object_detector_py> merge_simple_object_detectors(const pybind11::list&)’:
/root/dlib-master/tools/python/src/object_detection.cpp:132:20: error: cannot bind non-const lvalue reference of type ‘pybind11::detail::accessor<pybind11::detail::accessor_policies::sequence_item>&’ to an rvalue of type ‘pybind11::detail::generic_iterator<pybind11::detail::iterator_policies::sequence_slow_readwrite>::reference {aka pybind11::detail::accessor<pybind11::detail::accessor_policies::sequence_item>}’
     for (auto& d : detectors)
                    ^~~~~~~~~
gmake[2]: *** [CMakeFiles/dlib_python.dir/src/object_detection.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/dlib_python.dir/all] Error 2
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 257, in <module>
    'Topic :: Software Development',
  File "/usr/local/pypy60/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/pypy60/lib-python/2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/pypy60/lib-python/2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/pypy60/lib-python/2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/pypy60/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/pypy60/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/pypy60/lib-python/2.7/distutils/cmd.py", line 334, in run_command
    self.distribution.run_command(command)
  File "/usr/local/pypy60/lib-python/2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/pypy60/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/pypy60/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/local/pypy60/lib-python/2.7/distutils/cmd.py", line 334, in run_command
    self.distribution.run_command(command)
  File "/usr/local/pypy60/lib-python/2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/pypy60/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/local/pypy60/lib-python/2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/local/pypy60/lib-python/2.7/distutils/cmd.py", line 334, in run_command
    self.distribution.run_command(command)
  File "/usr/local/pypy60/lib-python/2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 133, in run
    self.build_extension(ext)
  File "setup.py", line 173, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "/usr/local/pypy60/lib-python/2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)

 

```
How do I deal with it?
Does Dlib support pypy?

**Comment by davisking** [comment]
This seems like a bug in your compiler. 

I just changed the code to work around it.  Try it now.

**Comment by blacksun1977** [comment]
Thanks alot !
but aother error found 
```
[ 90%] Building CXX object CMakeFiles/dlib_python.dir/src/rectangles.cpp.o
[ 91%] Building CXX object CMakeFiles/dlib_python.dir/src/object_detection.cpp.o
In file included from /root/dlib-master/dlib/../dlib/matrix.h:11:0,
                 from /root/dlib-master/dlib/../dlib/python/numpy_image.h:8,
                 from /root/dlib-master/dlib/../dlib/python.h:9,
                 from /root/dlib-master/tools/python/src/rectangles.cpp:4:
/root/dlib-master/dlib/../dlib/matrix/matrix_la.h: In function ‘long int dlib::svd4(dlib::svd_u_mode, bool, const dlib::matrix_exp<EXP>&, dlib::matrix<typename EXP::type, uM, uN, MM1, L1>&, dlib::matrix<typename EXP::type, qN, qX, MM2, L1>&, dlib::matrix<typename EXP::type, vM, vN, MM3, L1>&) [with EXP = dlib::matrix_op<dlib::op_trans<dlib::matrix_op<dlib::op_trans<dlib::matrix<double, 1, 2> > > > >; long int qN = 1; long int qX = 1; long int uM = 1; long int uN = 1; long int vM = 2; long int vN = 1; MM1 = dlib::memory_manager_stateless_kernel_1<char>; MM2 = dlib::memory_manager_stateless_kernel_1<char>; MM3 = dlib::memory_manager_stateless_kernel_1<char>; L1 = dlib::row_major_layout]’:
/root/dlib-master/dlib/../dlib/matrix/matrix_la.h:225:32: warning: iteration 1 invokes undefined behavior [-Waggressive-loop-optimizations]
             y = abs(q(i)) + abs(e(i));
                             ~~~^~~~~~
/root/dlib-master/dlib/../dlib/matrix/matrix_la.h:163:20: note: within this loop
         for (i=0; i<n; i++)
                   ~^~
[ 92%] Building CXX object CMakeFiles/dlib_python.dir/src/shape_predictor.cpp.o
[ 93%] Building CXX object CMakeFiles/dlib_python.dir/src/correlation_tracker.cpp.o
/root/dlib-master/tools/python/src/shape_predictor.cpp: In function ‘std::shared_ptr<dlib::full_object_detection> full_obj_det_init(const dlib::rectangle&, pybind11::list&)’:
/root/dlib-master/tools/python/src/shape_predictor.cpp:75:23: error: cannot bind non-const lvalue reference of type ‘pybind11::detail::accessor<pybind11::detail::accessor_policies::sequence_item>&’ to an rvalue of type ‘pybind11::detail::generic_iterator<pybind11::detail::iterator_policies::sequence_slow_readwrite>::reference {aka pybind11::detail::accessor<pybind11::detail::accessor_policies::sequence_item>}’
     for (auto& item : pyparts)
                       ^~~~~~~
gmake[2]: *** [CMakeFiles/dlib_python.dir/src/shape_predictor.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/dlib_python.dir/all] Error 2
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 257, in <module>
    'Topic :: Software Development',
  File "/usr/local/pypy60/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/pypy60/lib-python/2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/pypy60/lib-python/2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/pypy60/lib-python/2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/pypy60/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/pypy60/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/pypy60/lib-python/2.7/distutils/cmd.py", line 334, in run_command
    self.distribution.run_command(command)
  File "/usr/local/pypy60/lib-python/2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/pypy60/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/pypy60/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/local/pypy60/lib-python/2.7/distutils/cmd.py", line 334, in run_command
    self.distribution.run_command(command)
  File "/usr/local/pypy60/lib-python/2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/pypy60/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/local/pypy60/lib-python/2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/local/pypy60/lib-python/2.7/distutils/cmd.py", line 334, in run_command
    self.distribution.run_command(command)
  File "/usr/local/pypy60/lib-python/2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 133, in run
    self.build_extension(ext)
  File "setup.py", line 173, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "/usr/local/pypy60/lib-python/2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j3']' returned non-zero exit status 2
[root@019d6b1be0d6 dlib-master]# 
```
I build in Docker whit : Centos6.9, pypy 6.0.0, cmake 3.13.0-rc3, g++ (GCC) 7.1.0,

**Comment by blacksun1977** [comment]
@davisking i am not good at git, please pull request, thanks:)

**Comment by davisking** [comment]
No problem.  Thanks for reporting this.  I updated the code on github, so this shouldn't be a problem anymore.

**Comment by Dharani3110** [comment]
I download latest version dlib but I keep getting the above error.
![Screenshot (12)](https://user-images.githubusercontent.com/46337466/55668951-97fc3780-588e-11e9-8690-331078ee3d2e.png)

**Comment by Gab0** [comment]
I'm getting the exact same error of @Dharani3110, on pypy3.7.
