### ISSUE TITLE
failed to install using pip on ubuntu16 under anaconda

### ISSUE THREAD

**Issue by rnunziata** [davisking/dlib#1687]
```
 pip install dlib
Collecting dlib
  Using cached https://files.pythonhosted.org/packages/35/8d/e4ddf60452e2fb1ce3164f774e68968b3f110f1cb4cd353235d56875799e/dlib-19.16.0.tar.gz
Building wheels for collected packages: dlib
  Running setup.py bdist_wheel for dlib ... error
  Complete output from command /home/rjn/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-v2keat6o/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-1mx47y1d --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib/__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34)
  Invoking CMake setup: 'cmake /tmp/pip-install-v2keat6o/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-v2keat6o/dlib/build/lib.linux-x86_64-3.6 -DPYTHON_EXECUTABLE=/home/rjn/anaconda3/bin/python -DCMAKE_BUILD_TYPE=Release'
  -- The C compiler identification is GNU 5.5.0
  -- The CXX compiler identification is GNU 5.5.0
  -- Check for working C compiler: /home/linuxbrew/.linuxbrew/bin/cc
  -- Check for working C compiler: /home/linuxbrew/.linuxbrew/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /home/linuxbrew/.linuxbrew/bin/c++
  -- Check for working CXX compiler: /home/linuxbrew/.linuxbrew/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /home/rjn/anaconda3/bin/python (found version "3.6.8")
  -- Found PythonLibs: /home/rjn/anaconda3/lib/libpython3.6m.so
  -- Performing Test HAS_CPP14_FLAG
  -- Performing Test HAS_CPP14_FLAG - Success
  -- pybind11 v2.2.2
  -- Using CMake version: 3.5.1
  -- Compiling dlib version: 19.16.0
  -- SSE4 instructions can be executed by the host processor.
  -- AVX instructions can be executed by the host processor.
  -- Enabling AVX instructions
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- Looking for XOpenDisplay in /home/linuxbrew/.linuxbrew/lib/libX11.so;/home/linuxbrew/.linuxbrew/lib/libXext.so
  -- Looking for XOpenDisplay in /home/linuxbrew/.linuxbrew/lib/libX11.so;/home/linuxbrew/.linuxbrew/lib/libXext.so - found
  -- Looking for gethostbyname
  -- Looking for gethostbyname - found
  -- Looking for connect
  -- Looking for connect - found
  -- Looking for remove
  -- Looking for remove - found
  -- Looking for shmat
  -- Looking for shmat - found
  -- Looking for IceConnectionNumber in ICE
  -- Looking for IceConnectionNumber in ICE - found
  -- Found X11: /home/linuxbrew/.linuxbrew/lib/libX11.so
  -- Searching for BLAS and LAPACK
  -- Searching for BLAS and LAPACK
  -- Found PkgConfig: /home/linuxbrew/.linuxbrew/bin/pkg-config (found version "0.29.2")
  -- Checking for module 'cblas'
  --   No package 'cblas' found
  -- Checking for module 'lapack'
  --   No package 'lapack' found
  -- Looking for sys/types.h
  -- Looking for sys/types.h - found
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stddef.h
  -- Looking for stddef.h - found
  -- Check size of void*
  -- Check size of void* - done
  -- Found Intel MKL BLAS/LAPACK library
  -- Looking for sgesv
  -- Looking for sgesv - found
  -- Looking for sgesv_
  -- Looking for sgesv_ - found
  -- Found CUDA: /usr/local/cuda (found suitable version "10.1", minimum required is "7.5")
  -- Looking for cuDNN install...
  -- Found cuDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so
  -- Building a CUDA test project to see if your compiler is compatible with CUDA...
  -- Checking if you have the right version of cuDNN installed.
  -- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
  -- C++11 activated.
  CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  cusolver (ADVANCED)
      linked by target "dlib" in directory /tmp/pip-install-v2keat6o/dlib/dlib
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-v2keat6o/dlib/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-v2keat6o/dlib/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-v2keat6o/dlib/setup.py", line 257, in <module>
      'Topic :: Software Development',
    File "/home/rjn/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
      return distutils.core.setup(**attrs)
    File "/home/rjn/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/rjn/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/rjn/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/rjn/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/home/rjn/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/rjn/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/rjn/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/rjn/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/rjn/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-v2keat6o/dlib/setup.py", line 133, in run
      self.build_extension(ext)
    File "/tmp/pip-install-v2keat6o/dlib/setup.py", line 170, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "/home/rjn/anaconda3/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-v2keat6o/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-v2keat6o/dlib/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/home/rjn/anaconda3/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  
  ----------------------------------------
  Failed building wheel for dlib

```

**Comment by davisking** [comment]
Cuda 10.1 broke their install and cmake doesn't find it.  Try the latest dlib from github, I added a workaround for this issue.

**Comment by Davidrjx** [comment]
@rnunziata, maybe you can install cusolver development lib and header files as an attempt.
