### ISSUE TITLE
Windows10 dlib+python+cuda gpu configuration failed

### ISSUE THREAD

**Issue by BinGSSJ** [davisking/dlib#1708]
I have added CUDA and cmake to the system variables.Then I 
carried out “python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA“，but it failed.
The "1.txt" is its cout, when it is building...
[1.txt](https://github.com/davisking/dlib/files/3022594/1.txt)
The "2.txt" is its error.
[2.txt](https://github.com/davisking/dlib/files/3022599/2.txt)

I don't konw how to do.
please help me. 
Thanks a lot!

**Comment by BinGSSJ** [comment]
Error starting here

LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vcxproj]
jpeg.lib(jerror.c.obj) : warning LNK4217: locally defined symbol exit imported in function error_exit [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vcxproj]
jpeg.lib(jerror.c.obj) : warning LNK4217: locally defined symbol __acrt_iob_func imported in function output_message [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.
vcxproj]
jpeg.lib(jerror.c.obj) : warning LNK4217: locally defined symbol __stdio_common_vfprintf imported in function _vfprintf_l [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_py
thon.vcxproj]
jpeg.lib(jerror.c.obj) : warning LNK4217: locally defined symbol __stdio_common_vsprintf imported in function _vsnprintf_l [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_p
ython.vcxproj]
jpeg.lib(jdatasrc.c.obj) : warning LNK4217: locally defined symbol fread imported in function fill_input_buffer [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vcxpr
oj]
jpeg.lib(jmemansi.c.obj) : warning LNK4049: locally defined symbol fread imported [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vcxproj]
jpeg.lib(jdatadst.c.obj) : warning LNK4217: locally defined symbol free imported in function empty_mem_output_buffer [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.
vcxproj]
jpeg.lib(jmemansi.c.obj) : warning LNK4049: locally defined symbol free imported [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vcxproj]
jpeg.lib(jdatadst.c.obj) : warning LNK4217: locally defined symbol malloc imported in function empty_mem_output_buffer [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_pytho
n.vcxproj]
jpeg.lib(jmemansi.c.obj) : warning LNK4049: locally defined symbol malloc imported [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vcxproj]
jpeg.lib(jdatadst.c.obj) : warning LNK4217: locally defined symbol ferror imported in function term_destination [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vcxpr
oj]
jpeg.lib(jdatadst.c.obj) : warning LNK4217: locally defined symbol fflush imported in function term_destination [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vcxpr
oj]
jpeg.lib(jdatadst.c.obj) : warning LNK4217: locally defined symbol fwrite imported in function empty_output_buffer [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vc
xproj]
jpeg.lib(jmemansi.c.obj) : warning LNK4049: locally defined symbol fwrite imported [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vcxproj]
jpeg.lib(jdmarker.c.obj) : warning LNK4217: locally defined symbol strncpy imported in function get_lse [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vcxproj]
jpeg.lib(jmemansi.c.obj) : warning LNK4049: locally defined symbol strncpy imported [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vcxproj]
jpeg.lib(jmemmgr.c.obj) : warning LNK4217: locally defined symbol getenv imported in function jinit_memory_mgr [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vcxpro
j]
jpeg.lib(jmemmgr.c.obj) : warning LNK4217: locally defined symbol __stdio_common_vsscanf imported in function _vsscanf_l [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_pyt
hon.vcxproj]
jpeg.lib(jmemansi.c.obj) : warning LNK4217: locally defined symbol fclose imported in function close_backing_store [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vc
xproj]
jpeg.lib(jmemansi.c.obj) : warning LNK4217: locally defined symbol fseek imported in function read_backing_store [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_python.vcxp
roj]
jpeg.lib(jmemansi.c.obj) : error LNK2019: unresolved external symbol __imp_tmpfile referenced in function jpeg_open_backing_store [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release
\dlib_python.vcxproj]
D:\dlib-19.16\dlib-19.16\build\lib.win-amd64-3.7\dlib.cp37-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals [D:\dlib-19.16\dlib-19.16\build\temp.win-amd64-3.7\Release\dlib_pytho
n.vcxproj]
Traceback (most recent call last):
  File "setup.py", line 257, in <module>
    'Topic :: Software Development',
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 133, in run
    self.build_extension(ext)
  File "setup.py", line 173, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "D:\ProgramData\Miniconda3\envs\tensorflow-gpu\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.

**Comment by BinGSSJ** [comment]
omg，I used to use the dlib official website before. I don't know why it has not been successful. When I switched to your library, it was successful. This is incredible.
