### ISSUE TITLE
no run python build

### ISSUE THREAD

**Issue by bluems** [davisking/dlib#1738]
## Expected Behavior
1. git clone this repo and run command "python setup.py -G "Visual Studio 14 2015" install" 

## Current Behavior
(faceswap) C:\Users\bsh\dlib>python setup.py -G "Visual Studio 14 2015 Win64" install --clean
running install
running bdist_egg
running egg_info
writing dlib.egg-info\PKG-INFO
writing dependency_links to dlib.egg-info\dependency_links.txt
writing top-level names to dlib.egg-info\top_level.txt
package init file 'dlib\__init__.py' not found (or not a regular file)
reading manifest file 'dlib.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dlib.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Removing old directory C:\Users\bsh\dlib\build\temp.win-amd64-3.6\Release
Building extension for Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
Invoking CMake setup: 'cmake C:\Users\bsh\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\bsh\dlib\build\lib.win-amd64-3.6 -DPYTHON_EXECUTABLE=C:\Users\bsh\Anaconda3\envs\faceswap\python.exe -G Visual Studio 14 2015 Win64 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\bsh\dlib\build\lib.win-amd64-3.6 -A x64'
-- Selecting Windows SDK version  to target Windows 10.0.17134.
CMake Error in CMakeLists.txt:
  Generator

    Visual Studio 14 2015 Win64

  does not support platform specification, but platform

    x64

  was specified.

-- Configuring incomplete, errors occurred!
See also "C:/Users/bsh/dlib/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 261, in <module>
    'Topic :: Software Development',
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 135, in run
    self.build_extension(ext)
  File "setup.py", line 172, in build_extension
    subprocess.check_call(cmake_setup, cwd=build_folder)
  File "C:\Users\bsh\Anaconda3\envs\faceswap\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\bsh\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\bsh\\dlib\\build\\lib.win-amd64-3.6', '-DPYTHON_EXECUTABLE=C:\\Users\\bsh\\Anaconda3\\envs\\faceswap\\python.exe', '-G', 'Visual Studio 14 2015 Win64', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\bsh\\dlib\\build\\lib.win-amd64-3.6', '-A', 'x64']' returned non-zero exit status 1.

## Steps to Reproduce
Installed list:
1. Python 3.6.8
2. Anaconda latest version
3. nVidia CUDA 10.0
4. CMake 3.8
5. cuDNN 7.5
6. Visual Studio 2015

* **Version**: latest
* **Where did you get dlib**: failed both official and github
* **Platform**: Windows 10 64bit
* **Compiler**: Built-in compiler (Visual Studio 2015)

**Comment by davisking** [comment]
Run `python setup.py install --clean`. Don't give -G

**Comment by bluems** [comment]
@davisking When didn't give -G, script show CXX compiler not found.

**Comment by davisking** [comment]
Sounds like your visual studio install is broken.  Maybe you didn't install the C++ compiler but installed the C# version of visual studio.

**Comment by bluems** [comment]
> Sounds like your visual studio install is broken. Maybe you didn't install the C++ compiler but installed the C# version of visual studio.

Thanks. I was show "CXX not found"
but, I installed both 2017(Origin installed) and 2015(additional only dlib) so how do I select VS Version?
setup.py is auto-selecting VS 2017 Compiler. :(
