### ISSUE TITLE
Unable to use cuda (gpu)

### ISSUE THREAD

**Issue by quentinkoh** [davisking/dlib#1762]
## Expected Behavior

Expecting dlib to use gpu, however, during installation of setup.py on command prompt, it returned the message that dlib on my system will not use cuda.

The setup.py was able to find cuda and cudnn on my system.

## Current Behavior

The main error message returned for dlib not able to use cuda was - 'cuda was found but your compiler failed to compile a simple cuda program so dlib isn't going to use cuda.'

I've read through some similar issues and they mentioned to use VS 2017 or 2015 and I've tried both (I tried with VS 2019 initially). The command prompt message below was on VS 2015.

## Steps to Reproduce

* **Version**: 
19.17.99

* **Where did you get dlib**: 
Did a git clone and tried installing via setup.py

* **Platform**: 
Windows 10 (64-bit)
Python (3.6.5)
Conda (4.5.4)
VS Build Tools (2015)
CMake (3.14.3)

* **Compiler**: 

* **Message returned on command prompt:**

```
C:\Users\Quentin Koh>git clone https://github.com/davisking/dlib.git
Cloning into 'dlib'...
remote: Enumerating objects: 47205, done.
remote: Total 47205 (delta 0), reused 0 (delta 0), pack-reused 47205
Receiving objects: 100% (47205/47205), 22.00 MiB | 4.35 MiB/s, done.
Resolving deltas: 100% (33301/33301), done.
Checking out files: 100% (2142/2142), done.

C:\Users\Quentin Koh>
C:\Users\Quentin Koh>cd dlib

C:\Users\Quentin Koh\dlib>python setup.py install
running install
running bdist_egg
running egg_info
creating dlib.egg-info
writing dlib.egg-info\PKG-INFO
writing dependency_links to dlib.egg-info\dependency_links.txt
writing top-level names to dlib.egg-info\top_level.txt
writing manifest file 'dlib.egg-info\SOURCES.txt'
package init file 'dlib\__init__.py' not found (or not a regular file)
reading manifest file 'dlib.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 11: path 'tools/python/build*/' cannot end with '/'

warning: manifest_maker: MANIFEST.in, line 12: path 'dlib/test/' cannot end with '/'

writing manifest file 'dlib.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Building extension for Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Invoking CMake setup: 'cmake C:\Users\Quentin Koh\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Quentin Koh\dlib\build\lib.win-amd64-3.6 -DPYTHON_EXECUTABLE=C:\Users\Quentin Koh\Anaconda3\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\Quentin Koh\dlib\build\lib.win-amd64-3.6 -A x64'
-- Building for: Visual Studio 14 2015
-- Selecting Windows SDK version  to target Windows 10.0.17763.
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/Users/Quentin Koh/Anaconda3/python.exe (found version "3.6.5")
-- Found PythonLibs: C:/Users/Quentin Koh/Anaconda3/libs/Python36.lib
-- pybind11 v2.2.2
-- Using CMake version: 3.14.3
-- Compiling dlib version: 19.17.99
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Enabling SSE2 instructions
-- Found system copy of libpng: C:/Users/Quentin Koh/Anaconda3/Library/lib/libpng.lib;C:/Users/Quentin Koh/Anaconda3/Library/lib/z.lib
-- Found system copy of libjpeg: C:/Users/Quentin Koh/Anaconda3/Library/lib/jpeg.lib
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- FOUND libiomp5md.dll: C:/Users/Quentin Koh/Anaconda3/Library/bin/libiomp5md.dll
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found BLAS: C:/Users/Quentin Koh/Anaconda3/Library/lib/mkl_intel_lp64_dll.lib;C:/Users/Quentin Koh/Anaconda3/Library/lib/libiomp5md.lib;C:/Users/Quentin Koh/Anaconda3/Library/lib/mkl_intel_thread_dll.lib;C:/Users/Quentin Koh/Anaconda3/Library/lib/mkl_core_dll.lib
-- Looking for sgesv
-- Looking for sgesv - found
-- Looking for sgesv_
-- Looking for sgesv_ - found
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0 (found suitable version "9.0", minimum required is "7.5")
-- Looking for cuDNN install...
-- Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudnn.lib
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- *****************************************************************************************************************
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA.
-- *** The output of the failed CUDA test compile is shown below:
-- ***   Change Dir: C:/Users/Quentin Koh/dlib/build/temp.win-amd64-3.6/Release/dlib_build/cuda_test_build
   ***
   ***   Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe ALL_BUILD.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m
   ***   Microsoft (R) Build Engine version 14.0.25420.1
   ***   Copyright (C) Microsoft Corporation. All rights reserved.
   ***
   ***     Checking Build System
   ***     CMake does not need to re-run because C:/Users/Quentin Koh/dlib/build/temp.win-amd64-3.6/Release/dlib_build/cuda_test_build/CMakeFiles/generate.stamp is up-to-date.
   ***     Building NVCC (Device) object CMakeFiles/cuda_test.dir/Debug/cuda_test_generated_cuda_test.cu.obj
   ***     nvcc fatal   : Could not set up the environment for Microsoft Visual Studio using 'C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/../../VC/bin/amd64/vcvars64.bat'
   ***     CMake Error at cuda_test_generated_cuda_test.cu.obj.Debug.cmake:215 (message):
   ***       Error generating C:/Users/Quentin
   ***       Koh/dlib/build/temp.win-amd64-3.6/Release/dlib_build/cuda_test_build/CMakeFiles/cuda_test.dir//Debug/cuda_test_generated_cuda_test.cu.obj
   ***
   ***
   ***   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\Quentin Koh\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\cuda_test.vcxproj]
   ***
-- *****************************************************************************************************************
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Quentin Koh/dlib/build/temp.win-amd64-3.6/Release
Invoking CMake build: 'cmake --build . --config Release -- /m'
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  CMake does not need to re-run because C:/Users/Quentin Koh/dlib/build/temp.win-amd64-3.6/Release/CMakeFiles/generate.stamp is up-to-date.
  CMake does not need to re-run because C:/Users/Quentin Koh/dlib/build/temp.win-amd64-3.6/Release/pybind11_build/CMakeFiles/generate.stamp is up-to-date.
  CMake does not need to re-run because C:/Users/Quentin Koh/dlib/build/temp.win-amd64-3.6/Release/dlib_build/CMakeFiles/generate.stamp is up-to-date.
  Building Custom Rule C:/Users/Quentin Koh/dlib/dlib/CMakeLists.txt
  CMake does not need to re-run because C:/Users/Quentin Koh/dlib/build/temp.win-amd64-3.6/Release/dlib_build/CMakeFiles/generate.stamp is up-to-date.
  base64_kernel_1.cpp
  bigint_kernel_1.cpp
  bigint_kernel_2.cpp
  bit_stream_kernel_1.cpp
  entropy_decoder_kernel_1.cpp
  entropy_decoder_kernel_2.cpp
  entropy_encoder_kernel_1.cpp
  entropy_encoder_kernel_2.cpp
  md5_kernel_1.cpp
  tokenizer_kernel_1.cpp
  unicode.cpp
  image_dataset_metadata.cpp
  mnist.cpp
  global_function_search.cpp
  kalman_filter.cpp
  test_for_odr_violations.cpp
  auto.cpp
  sockets_kernel_1.cpp
  bsp.cpp
  dir_nav_kernel_1.cpp
  dir_nav_kernel_2.cpp
  dir_nav_extensions.cpp
  linker_kernel_1.cpp
  extra_logger_headers.cpp
  logger_kernel_1.cpp
  logger_config_file.cpp
  misc_api_kernel_1.cpp
  misc_api_kernel_2.cpp
  sockets_extensions.cpp
  sockets_kernel_2.cpp
  sockstreambuf.cpp
  sockstreambuf_unbuffered.cpp
  server_kernel.cpp
  server_iostream.cpp
  server_http.cpp
  multithreaded_object_extension.cpp
  threaded_object_extension.cpp
  threads_kernel_1.cpp
  threads_kernel_2.cpp
  threads_kernel_shared.cpp
  thread_pool_extension.cpp
  async.cpp
  timer.cpp
  stack_trace.cpp
  cpu_dlib.cpp
  tensor_tools.cpp
  fonts.cpp
  widgets.cpp
  drawable.cpp
  canvas_drawing.cpp
  style.cpp
  base_widgets.cpp
  gui_core_kernel_1.cpp
  gui_core_kernel_2.cpp
  png_loader.cpp
  save_png.cpp
  jpeg_loader.cpp
  save_jpeg.cpp
  dlib.vcxproj -> C:\Users\Quentin Koh\dlib\build\temp.win-amd64-3.6\Release\dlib_build\Release\dlib19.17.99_release_64bit_msvc1900.lib
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(403,5): error MSB3191: Unable to create directory "C:\Users\Quentin Koh\dlib\build\lib.win-amd64-3.6\". Cannot creat
e "C:\Users\Quentin Koh\dlib\build\lib.win-amd64-3.6" because a file or directory with the same name already exists. [C:\Users\Quentin Koh\dlib\build\temp.win-amd64-3.6\Release\dlib_python.vcxproj]
Traceback (most recent call last):
  File "setup.py", line 261, in <module>
    'Topic :: Software Development',
  File "C:\Users\Quentin Koh\Anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Quentin Koh\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Quentin Koh\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\Quentin Koh\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Quentin Koh\Anaconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\Quentin Koh\Anaconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\Quentin Koh\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Quentin Koh\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Quentin Koh\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\Quentin Koh\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\Users\Quentin Koh\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Quentin Koh\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Quentin Koh\Anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\Quentin Koh\Anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\Quentin Koh\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Quentin Koh\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 135, in run
    self.build_extension(ext)
  File "setup.py", line 175, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "C:\Users\Quentin Koh\Anaconda3\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.

C:\Users\Quentin Koh\dlib>
```

**Comment by quentinkoh** [comment]
any readers able to help please?

**Comment by facug91** [comment]
I don't know what the problem is, but it might be something about your environment variables. Maybe installing so many versions of VS, you have some problem there.  
Sorry I can't help you more. And this doesn't seem to be a dlib problem, but a VS/CUDA installation one, you could look for a little more on that side.

**Comment by gasvn** [comment]
same problem here. Does anyone has a solution?

**Comment by davisking** [comment]
I think this was happening because, for some reason, some versions of visual studio/cmake together don't create the output binary folder in some cases (wtf), and when cmake then goes to copy some output files into the folder there is an error.  I pushed a change last night to the cmake scripts that forces explicit creation of the output folder, which seems to address this kind of thing.

**Comment by racinmat** [comment]
Happened to me too.
So, should I use the master version, or wait until it is released as stable version? Is there some ETA for that?

**Comment by davisking** [comment]
Use the master version.
