### ISSUE TITLE
Disabling CUDA support for dlib.

### ISSUE THREAD

**Issue by Dentrax** [davisking/dlib#1781]
## Expected Behavior

Trying to compile with `GPU` support from repository.

## Current Behavior

```
running install
running bdist_egg
running egg_info
writing dlib.egg-info/PKG-INFO
writing dependency_links to dlib.egg-info/dependency_links.txt
writing top-level names to dlib.egg-info/top_level.txt
package init file 'dlib/__init__.py' not found (or not a regular file)
reading manifest file 'dlib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tools/python/build*/'
writing manifest file 'dlib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Building extension for Python 3.7.3 (default, Mar 26 2019, 21:43:19) 
Invoking CMake setup: 'cmake /home/dentrax/Projects/GitHub/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/dentrax/Projects/GitHub/dlib/build/lib.linux-x86_64-3.7 -DPYTHON_EXECUTABLE=/usr/bin/python3 -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1 -DCMAKE_BUILD_TYPE=Release'
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python3 (found version "3.7.3") 
-- Found PythonLibs: /usr/lib/libpython3.7m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.2.2
-- Using CMake version: 3.14.3
-- Compiling dlib version: 19.17.99
-- SSE4 instructions can be executed by the host processor.
-- AVX instructions can be executed by the host processor.
-- Enabling AVX instructions
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found system copy of libpng: /usr/lib/libpng.so;/usr/lib/libz.so
-- Found system copy of libjpeg: /usr/lib/libjpeg.so
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.1") 
-- Checking for module 'cblas'
--   Found cblas, version 3.8.0
-- Checking for module 'lapack'
--   Found lapack, version 3.8.0
-- Found BLAS and LAPACK via pkg-config
-- Found CUDA: /opt/cuda (found suitable version "10.0", minimum required is "7.5") 
-- Looking for cuDNN install...
-- Found cuDNN: /usr/lib/libcudnn.so
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- *****************************************************************************************************************
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA. 
-- *** The output of the failed CUDA test compile is shown below: 
-- ***   Change Dir: /home/dentrax/Projects/GitHub/dlib/build/temp.linux-x86_64-3.7/dlib_build/cuda_test_build
   ***   
   ***   Run Build Command(s):/usr/bin/make 
   ***   [ 50%] Building NVCC (Device) object CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o
   ***   In file included from /opt/cuda/include/cuda_runtime.h:83,
   ***                    from <command-line>:
   ***   /opt/cuda/include/crt/host_config.h:129:2: error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!
   ***    #error -- unsupported GNU version! gcc versions later than 7 are not supported!
   ***     ^~~~~
   ***   CMake Error at cuda_test_generated_cuda_test.cu.o.cmake:215 (message):
   ***     Error generating
   ***     /home/dentrax/Projects/GitHub/dlib/build/temp.linux-x86_64-3.7/dlib_build/cuda_test_build/CMakeFiles/cuda_test.dir//./cuda_test_generated_cuda_test.cu.o
   ***   
   ***   
   ***   make[2]: *** [CMakeFiles/cuda_test.dir/build.make:65: CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o] Error 1
   ***   make[1]: *** [CMakeFiles/Makefile2:72: CMakeFiles/cuda_test.dir/all] Error 2
   ***   make: *** [Makefile:84: all] Error 2
   ***   
-- *****************************************************************************************************************
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dentrax/Projects/GitHub/dlib/build/temp.linux-x86_64-3.7
Invoking CMake build: 'cmake --build . --config Release -- -j4'
Scanning dependencies of target dlib
...
...
...
```

## Steps to Reproduce

1. `mkdir build; cd build; cmake .. -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1; cmake --build .`

2. `python3 setup.py install --set DLIB_USE_CUDA=1 --set USE_AVX_INSTRUCTIONS=1 --user`

* **Version**: https://github.com/davisking/dlib/commit/8001b924e63ac920a9047610ece2e4e6266e8a4c

* **Where did you get dlib**: `Cloned from repository`

* **Platform**: `Arch x64`

* **Compiler**: `gcc 8.3.0`

I think i need to compile with `gcc-7`. How can I compile with `gcc-7` instead of `gcc-8`? When will `gcc-8` be supported?

**Comment by arrufat** [comment]
Hi, fellow Arch user. I think I can help you.
I am able to build dlib with latest versions of GCC and CUDA from the Official repositories, that is:
- gcc-8.3.0-1
- cuda-10.1.168
- cudnn-7.5.1.10

From what I see from your log, you don't have the latest version of CUDA (your log shows 10.0 instead of 10.1), which is not compatible with GCC > 7.
You have two options:
- update your system to use the latest version of CUDA
- if the above is not possible, you need to get GCC 7
  - from [AUR](https://aur.archlinux.org/packages/gcc7/)
  - from the Arch Linux Archive: [gcc7](https://archive.archlinux.org/packages/g/gcc7/) & [gcc7-libs](https://archive.archlinux.org/packages/g/gcc7-libs/)

Then you will need to build dlib like:
```
CC=gcc-7 cmake .. -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1
```

However, I would recommend updating your CUDA package :)

**Comment by Dentrax** [comment]
Hey, sorry for late reply.

Project does not run with `cuda-10.1` when we update cuda package. Because Tensorflow is not supporting `cuda-10.1` yet. Also It gives a similar error at the time I compiled with the `gcc-7`.  How can we compile the `dlib` using `cuda-10.0`? @davisking @arrufat

Thank you!

Tensorflow Error:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 17, in <module>
    import cyclens
  File "/home/m1311/Projects/bitirme/cyclens-server/cyclens/__init__.py", line 24, in <module>
    from .Cyclens import Cyclens
  File "/home/m1311/Projects/bitirme/cyclens-server/cyclens/Cyclens.py", line 7, in <module>
    import keras
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/m1311/Projects/bitirme/cyclens-server/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
```

**Comment by arrufat** [comment]
Have you tried the tensorflow python package from the official Arch Linux repositories? It supports CUDA 10.1.

**Comment by Dentrax** [comment]
@arrufat 

We are using `tensorflow` in our custom _virtualenv_ build. In this case, i think we can't access that python package from within the project? By the way, what exactly is the name and version of the package you said? Thank you!

**Comment by arrufat** [comment]
You can just use the latest tensorflow version from the official repositories: `python-tensorflow-opt-cuda` `v1.13.1-5`.
However, if you're not using the official packages, you're on your own... You need to figure out a configuration that works for you. Usually, if you're not building tensorflow from source, you need to have the same CUDA version that was used to build it. Apparently CUDA 10.0 in your case. Then since that version is not compatible with `gcc` 8, you will need to install `gcc7` as I said, and build dlib with it. That's all I can say...
