### ISSUE TITLE
Python Compilation Error

### ISSUE THREAD

**Issue by minimalisticMe** [davisking/dlib#1787]
Hey @davisking,

I'm on Windows 10 x64, Python 3.7, CUDA 10.1, cuDNN 7.6, Visual Studio 2019 v16.1.1, cmake 3.14.4, latest Intel MKL and TBB and trying to build dlib for python with `python setup.py install`.

Before I post the problem: Compiling dlib for c++ only is working!

So when building it for python, I get the following output:

```
running install
running bdist_egg
running egg_info
creating dlib.egg-info
writing dlib.egg-info\PKG-INFO
writing dependency_links to dlib.egg-info\dependency_links.txt
writing top-level names to dlib.egg-info\top_level.txt
writing manifest file 'dlib.egg-info\SOURCES.txt'
package init file 'dlib\__init__.py' not found (or not a regular file)
reading manifest file 'dlib.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 11: path 'tools/python/build*/' cannot end with '/'

warning: manifest_maker: MANIFEST.in, line 12: path 'dlib/test/' cannot end with '/'

writing manifest file 'dlib.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Building extension for Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
Invoking CMake setup: 'cmake D:\Dev\Cplusplus\dlib\dlib-src\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\Dev\Cplusplus\dlib\dlib-src\build\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=C:\Users\user\AppData\Local\Programs\Python\Python37\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=D:\Dev\Cplusplus\dlib\dlib-src\build\lib.win-amd64-3.7 -A x64'
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
-- The C compiler identification is MSVC 19.21.27702.2
-- The CXX compiler identification is MSVC 19.21.27702.2
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/Users/user/AppData/Local/Programs/Python/Python37/python.exe (found version "3.7.3") 
-- Found PythonLibs: C:/Users/user/AppData/Local/Programs/Python/Python37/libs/Python37.lib
-- pybind11 v2.2.2
-- Using CMake version: 3.14.4
-- Compiling dlib version: 19.17.99
-- SSE4 instructions can be executed by the host processor.
-- AVX instructions can be executed by the host processor.
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Enabling AVX instructions
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- FOUND libiomp5md.dll: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/redist/intel64/compiler/libiomp5md.dll
-- Found Intel MKL BLAS/LAPACK library
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Looking for sgesv
-- Looking for sgesv - found
-- Looking for sgesv_
-- Looking for sgesv_ - found
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 (found suitable version "10.1", minimum required is "7.5") 
-- Looking for cuDNN install...
-- Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cudnn.lib
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- Checking if you have the right version of cuDNN installed.
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Dev/Cplusplus/dlib/dlib-src/build/temp.win-amd64-3.7/Release
Invoking CMake build: 'cmake --build . --config Release -- /m'
Microsoft (R)-Build-Engine, Version 16.1.76+g14b0a930a7 fr .NET Framework
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  Checking Build System
  CMake does not need to re-run because D:/Dev/Cplusplus/dlib/dlib-src/build/temp.win-amd64-3.7/Release/CMakeFiles/generate.stamp is up-to-date.
  CMake does not need to re-run because D:/Dev/Cplusplus/dlib/dlib-src/build/temp.win-amd64-3.7/Release/pybind11_build/CMakeFiles/generate.stamp is up-to-date.
  CMake does not need to re-run because D:/Dev/Cplusplus/dlib/dlib-src/build/temp.win-amd64-3.7/Release/dlib_build/CMakeFiles/generate.stamp is up-to-date.
  Building NVCC (Device) object dlib_build/CMakeFiles/dlib.dir/cuda/Release/dlib_generated_cuda_dlib.cu.obj
  cuda_dlib.cu
  cuda_dlib.cu
  Building NVCC (Device) object dlib_build/CMakeFiles/dlib.dir/cuda/Release/dlib_generated_cusolver_dlibapi.cu.obj
  cusolver_dlibapi.cu
  cusolver_dlibapi.cu
  Building Custom Rule D:/Dev/Cplusplus/dlib/dlib-src/dlib/CMakeLists.txt
  CMake is re-running because D:/Dev/Cplusplus/dlib/dlib-src/build/temp.win-amd64-3.7/Release/dlib_build/CMakeFiles/generate.stamp is out-of-date.
    the file 'D:/Dev/Cplusplus/dlib/dlib-src/build/temp.win-amd64-3.7/Release/dlib_build/CMakeFiles/dlib.dir/cuda/dlib_generated_cuda_dlib.cu.obj.depend'
    is newer than 'D:/Dev/Cplusplus/dlib/dlib-src/build/temp.win-amd64-3.7/Release/dlib_build/CMakeFiles/generate.stamp.depend'
    result='-1'
  -- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
  -- pybind11 v2.2.2
  -- Using CMake version: 3.14.4
  -- Compiling dlib version: 19.17.99
  -- SSE4 instructions can be executed by the host processor.
  -- AVX instructions can be executed by the host processor.
  -- Enabling AVX instructions
  -- Searching for BLAS and LAPACK
  -- Searching for BLAS and LAPACK
  -- FOUND libiomp5md.dll: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/redist/intel64/compiler/libiomp5md.dll
  -- Found Intel MKL BLAS/LAPACK library
  -- Looking for cuDNN install...
  -- Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cudnn.lib
  -- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
  -- C++11 activated.
  -- Configuring done
  -- Generating done
  -- Build files have been written to: D:/Dev/Cplusplus/dlib/dlib-src/build/temp.win-amd64-3.7/Release
  base64_kernel_1.cpp
  bigint_kernel_1.cpp
  bigint_kernel_2.cpp
  bit_stream_kernel_1.cpp
  entropy_decoder_kernel_1.cpp
  entropy_decoder_kernel_2.cpp
  entropy_encoder_kernel_1.cpp
  entropy_encoder_kernel_2.cpp
  md5_kernel_1.cpp
  tokenizer_kernel_1.cpp
  unicode.cpp
  image_dataset_metadata.cpp
  mnist.cpp
  global_function_search.cpp
  kalman_filter.cpp
  test_for_odr_violations.cpp
  auto.cpp
  sockets_kernel_1.cpp
  bsp.cpp
  dir_nav_kernel_1.cpp
  dir_nav_kernel_2.cpp
  dir_nav_extensions.cpp
  linker_kernel_1.cpp
  extra_logger_headers.cpp
  logger_kernel_1.cpp
  logger_config_file.cpp
  misc_api_kernel_1.cpp
  misc_api_kernel_2.cpp
  sockets_extensions.cpp
  sockets_kernel_2.cpp
  sockstreambuf.cpp
  sockstreambuf_unbuffered.cpp
  server_kernel.cpp
  server_iostream.cpp
  server_http.cpp
  multithreaded_object_extension.cpp
  threaded_object_extension.cpp
  threads_kernel_1.cpp
  threads_kernel_2.cpp
  threads_kernel_shared.cpp
  thread_pool_extension.cpp
  async.cpp
  timer.cpp
  stack_trace.cpp
  cpu_dlib.cpp
  tensor_tools.cpp
  fonts.cpp
  widgets.cpp
  drawable.cpp
  canvas_drawing.cpp
  style.cpp
  base_widgets.cpp
  gui_core_kernel_1.cpp
  gui_core_kernel_2.cpp
  png_loader.cpp
  save_png.cpp
  jpeg_loader.cpp
  save_jpeg.cpp
  cudnn_dlibapi.cpp
  cublas_dlibapi.cpp
  curand_dlibapi.cpp
  cuda_data_ptr.cpp
  gpu_data.cpp
  arm_init.c
  filter_neon_intrinsics.c
  png.c
  pngerror.c
  pngget.c
  pngmem.c
  pngpread.c
  pngread.c
  pngrio.c
  pngrtran.c
  pngrutil.c
  pngset.c
  pngtrans.c
  pngwio.c
  pngwrite.c
  pngwtran.c
  pngwutil.c
  adler32.c
  compress.c
  crc32.c
  deflate.c
  gzclose.c
  gzread.c
  gzlib.c
  gzwrite.c
  infback.c
  inffast.c
  inflate.c
  inftrees.c
  trees.c
  uncompr.c
  zutil.c
  jaricom.c
  jcapimin.c
  jcapistd.c
  jcarith.c
  jccoefct.c
  jccolor.c
  jcdctmgr.c
  jchuff.c
  jcinit.c
  jcmainct.c
  jcmarker.c
  jcmaster.c
  jcomapi.c
  jcparam.c
  jcprepct.c
  jcsample.c
  jdapimin.c
  jdapistd.c
  jdarith.c
  jdatadst.c
  jdatasrc.c
  jdcoefct.c
  jdcolor.c
  jddctmgr.c
  jdhuff.c
  jdinput.c
  jdmainct.c
  jdmarker.c
  jdmaster.c
  jdmerge.c
  jdpostct.c
  jdsample.c
  jerror.c
  jfdctflt.c
  jfdctfst.c
D:\Dev\Cplusplus\dlib\dlib-src\dlib\external\libjpeg\jdatadst.c(185,60): warning C4267:  "=": Konvertierung von "size_t" nach "unsigned long", Datenverlust m”glich [D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_build\dlib.vcxproj]
D:\Dev\Cplusplus\dlib\dlib-src\dlib\external\libjpeg\jerror.c(193,1): warning C4996:  'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_build\dlib.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\stdio.h(1774): message :  Siehe Deklaration von "sprintf"jfdctint.c [D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_build\dlib.vcxproj]
D:\Dev\Cplusplus\dlib\dlib-src\dlib\external\libjpeg\jerror.c(195,1): warning C4996:  'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_build\dlib.vcxproj]
  jidctflt.c
  jidctfst.c
  jidctint.c
  jmemmgr.c
  jmemnobs.c
  jquant1.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\stdio.h(1774): message :  Siehe Deklaration von "sprintf" [D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_build\dlib.vcxproj]
D:\Dev\Cplusplus\dlib\dlib-src\dlib\external\libjpeg\jmemmgr.c(307,53): warning C4267:  "+=": Konvertierung von "size_t" nach "long", Datenverlust m”glich [D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_build\dlib.vcxproj]
  jquant2.c
D:\Dev\Cplusplus\dlib\dlib-src\dlib\external\libjpeg\jmemmgr.c(367,70): warning C4267:  "+=": Konvertierung von "size_t" nach "long", Datenverlust m”glich [D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_build\dlib.vcxproj]
  jutils.c
D:\Dev\Cplusplus\dlib\dlib-src\dlib\external\libjpeg\jmemmgr.c(977,46): warning C4267:  "-=": Konvertierung von "size_t" nach "long", Datenverlust m”glich [D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_build\dlib.vcxproj]
D:\Dev\Cplusplus\dlib\dlib-src\dlib\external\libjpeg\jmemmgr.c(991,46): warning C4267:  "-=": Konvertierung von "size_t" nach "long", Datenverlust m”glich [D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_build\dlib.vcxproj]
D:\Dev\Cplusplus\dlib\dlib-src\dlib\external\libjpeg\jmemmgr.c(1107,1): warning C4996:  'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_build\dlib.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\stdlib.h(1191): message :  Siehe Deklaration von "getenv" [D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_build\dlib.vcxproj]
D:\Dev\Cplusplus\dlib\dlib-src\dlib\external\libjpeg\jmemmgr.c(1110,1): warning C4996:  'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_build\dlib.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\stdio.h(2263): message :  Siehe Deklaration von "sscanf" [D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_build\dlib.vcxproj]
  dlib.vcxproj -> D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_build\Release\dlib19.17.99_release_64bit_msvc1921.lib
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(463,5): error MSB3191: Das Verzeichnis "D:\Dev\Cplusplus\dlib\dlib-src\build\lib.win-amd64-3.7\" kann nicht erstellt werden. "D:\Dev\Cplusplus\dlib\dlib-src\build\lib.win-amd64-3.7" kann nicht erstellt werden, da eine Datei oder ein Verzeichnis mit demselben Namen bereits vorhanden ist. [D:\Dev\Cplusplus\dlib\dlib-src\build\temp.win-amd64-3.7\Release\dlib_python.vcxproj]
Traceback (most recent call last):
  File "setup.py", line 261, in <module>
    'Topic :: Software Development',
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 135, in run
    self.build_extension(ext)
  File "setup.py", line 175, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.

```

The error says, that it cannot create a directory, as it already exists. I did a fresh check-out and investigating the issue further it seems, that for python there are two projects in the solution file. one called `dlib`, which is compiled without isses, the next one is called `dlib_python`. Now when opening the solution file that was created py the `setup.py` and building this project by myself, I run in the error, that the directory (where the solution file is in) already exists.

I might have done something wrong during the configuration, although if so - I don't know what.
What can I do about this issue?

**Comment by davisking** [comment]
I'm not able to reproduce this.  What happens if you delete all the dlib files and folders, get a new copy of dlib from github, and then run `python setup.py build`?  What happens if you then run `python setup.py install`?  Is it different?

**Comment by wemamawe** [comment]
@minimalisticMe It happend to me, I use Windows10 system, cmake,boost, and alway has error when install.
![978550692](https://user-images.githubusercontent.com/29365634/61944917-604a0480-afd1-11e9-9b8d-1848e6099289.jpg)

**Comment by minimalisticMe** [comment]
I found the issue.
There is a file called `lib.win-amd64-3.7`. Delete that and create a folder with the same name.
Then run the steup-script again and you are good to go.
