### ISSUE TITLE
Dlib/cudaMalloc() error 

### ISSUE THREAD

**Issue by flydragon2018** [davisking/dlib#1957]
IF YOU ARE REPORTING A BUG OR PROBLEM WITH DLIB THEN FILL OUT THE ENTIRE TEMPLATE BELOW.  ISSUES ASKING QUESTIONS ABOUT WHY SOMETHING DOESN'T WORK THAT FAIL TO FILL OUT THE ENTIRE TEMPLATE WILL BE CLOSED.

It is OK to suggest interesting improvements to dlib, even if you are not volunteering to implement them.  **However, the issue tracker is not a code writing service, do not ask for someone to write code for you.**  E.g. Do not ask for feature improvements to the example programs. **If there is some feature improvement you want in an example program then it's up to you to write it**.  

Before you ask a question, check Google for a solution, [the dlib FAQ](http://dlib.net/faq.html), or consult the dlib documentation.  Every single function in dlib is documented in detail.  If you obviously haven't read the documentation your issue will be closed.  

If you aren't reporting a bug or problem with dlib then delete this template and write whatever you want here.
 
 D:\Downloads\dlibopencvface> python encode_faces.py --dataset dataset --encodings encodings.pickle
[INFO] quantifying faces...
[INFO] processing image 1/75
[INFO] processing image 2/75
[INFO] processing image 3/75
[INFO] processing image 4/75
[INFO] processing image 5/75
[INFO] processing image 6/75
[INFO] processing image 7/75
[INFO] processing image 8/75
[INFO] processing image 9/75
[INFO] processing image 10/75
[INFO] processing image 11/75
[INFO] processing image 12/75
Traceback (most recent call last):
  File "encode_faces.py", line 45, in <module>
    model=args["detection_method"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\face_recognition\api.py", line 116, in face_locations
    return [_trim_css_to_bounds(_rect_to_css(face.rect), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, "cnn")]
  File "C:\ProgramData\Anaconda3\lib\site-packages\face_recognition\api.py", line 100, in _raw_face_locations
    return cnn_face_detector(img, number_of_times_to_upsample)

## Expected Behavior
should work fine.

## Current Behavior
RuntimeError: Error while calling cudaMalloc(&data, n) in file D:\dlib\dlib\cuda\cuda_data_ptr.cpp:58. code: 2, reason: out of memory 

## Steps to Reproduce
 
face_recognition+dlib+cuda.

* **Version**: 
* **Where did you get dlib**: 
* **Platform**: 
* **Compiler**:

**Comment by flydragon2018** [comment]
version 19.19
git clone github
ubuntu18 cuda10.2 
gcc 7.3.0
