### ISSUE TITLE
ValueError: path 'dlib/CMakeLists.txt/' cannot end with '/'

### ISSUE THREAD

**Issue by Thatchantique** [davisking/dlib#2038]
Hello !

I try to install dlib with : 

```sh
pip install https://files.pythonhosted.org/packages/0e/ce/f8a3cff33ac03a8219768f0694c5d703c8e037e6aba2e865f9bae22ed63c/dlib-19.8.1-cp36-cp36m-win_amd64.whl#sha256=794994fa2c54e7776659fddb148363a5556468a6d5d46be8dad311722d54bfcf
```

But when I try it I have : 
```sh
ERROR: dlib-19.8.1-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
```

And when I try to install with the source I find this : 
```sh
running install
running bdist_egg
running egg_info
writing dlib.egg-info\PKG-INFO
writing dependency_links to dlib.egg-info\dependency_links.txt
writing top-level names to dlib.egg-info\top_level.txt
package init file 'dlib\__init__.py' not found (or not a regular file)
reading manifest file 'dlib.egg-info\SOURCES.txt'
Traceback (most recent call last):
  File "setup.py", line 261, in <module>
    'Topic :: Software Development',
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 297, in run
    self.find_sources()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 304, in find_sources
    mm.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 535, in run
    self.add_defaults()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 579, in add_defaults
    self.read_manifest()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\sdist.py", line 220, in read_manifest
    self.filelist.append(line)
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 477, in append
    path = convert_path(item)
  File "C:\ProgramData\Anaconda3\lib\distutils\util.py", line 112, in convert_path
    raise ValueError("path '%s' cannot end with '/'" % pathname)
ValueError: path 'dlib/CMakeLists.txt/' cannot end with '/'
```
How can I fix this ?

**Comment by davisking** [comment]
Do `pip install dlib` instead.

**Comment by Thatchantique** [comment]
I have :
```sh
Command errored out with exit status 1
```

**Comment by Thatchantique** [comment]
It's only with my global environment in Python 3.7

**Comment by jetjodh** [comment]
@Thatchantique I am facing the exact same issue. Did you resolve this issue?
