### ISSUE TITLE
dlib compile error with CUDA 10.2 (identifier "dlib::sqrt_2" is undefined in device code)

### ISSUE THREAD

**Issue by vayunmathur** [davisking/dlib#2208]
## Expected Behavior

dlib should compile with CUDA

## Current Behavior

It does not compile
```
running install
running bdist_egg
running egg_info
writing tools/python\dlib.egg-info\PKG-INFO
writing dependency_links to tools/python\dlib.egg-info\dependency_links.txt
writing top-level names to tools/python\dlib.egg-info\top_level.txt
package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
reading manifest file 'tools/python\dlib.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tools\python\build*'
writing manifest file 'tools/python\dlib.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Building extension for Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Invoking CMake setup: 'cmake C:\Users\Vayun Mathur\OneDrive\Documents\code\python\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Vayun Mathur\OneDrive\Documents\code\python\dlib\build\lib.win-amd64-3.8 -DPYTHON_EXECUTABLE=C:\Users\Vayun Mathur\anaconda3\envs\AI\python.exe -DCMAKE_CXX_FLAGS=-DCUDA_HOST_COMPILER=/usr/bin/gcc-6 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\Vayun Mathur\OneDrive\Documents\code\python\dlib\build\lib.win-amd64-3.8 -A x64'      
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.27.29111.0
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/Users/Vayun Mathur/anaconda3/envs/AI/python.exe (found version "3.8.5") 
-- Found PythonLibs: C:/Users/Vayun Mathur/anaconda3/envs/AI/libs/Python38.lib
-- pybind11 v2.2.2
-- Using CMake version: 3.18.2
-- Compiling dlib version: 19.21.99
-- SSE4 instructions can be executed by the host processor.
-- AVX instructions can be executed by the host processor.
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Enabling AVX instructions
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE  
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2 (found suitable version "10.2", minimum required is "7.5") 
-- Looking for cuDNN install...
-- Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/lib/x64/cudnn.lib
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- Building a cuDNN test project to check if you have the right version of cuDNN installed...
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Vayun Mathur/OneDrive/Documents/code/python/dlib/build/temp.win-amd64-3.8/Release
Invoking CMake build: 'cmake --build . --config Release -- /m'
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building NVCC (Device) object dlib_build/CMakeFiles/dlib.dir/cuda/Release/dlib_generated_cuda_dlib.cu.obj
  cuda_dlib.cu
C:/Users/Vayun Mathur/OneDrive/Documents/code/python/dlib/dlib/cuda/cuda_dlib.cu(1504): error : identifier "dlib::pi" is undefined in device code [C:\Users\Vayun Mathur\OneDrive\Documents\code\python\dlib\build\temp.win-amd64-3.8\Release
\dlib_build\dlib.vcxproj]
  
C:/Users/Vayun Mathur/OneDrive/Documents/code/python/dlib/dlib/cuda/cuda_dlib.cu(1504): error : identifier "dlib::sqrt_2" is undefined in device code [C:\Users\Vayun Mathur\OneDrive\Documents\code\python\dlib\build\temp.win-amd64-3.8\Rel 
ease\dlib_build\dlib.vcxproj]
  
  2 errors detected in the compilation of "C:/Users/VAYUNM~1/AppData/Local/Temp/tmpxft_00005f64_00000000-10_cuda_dlib.cpp1.ii".
  cuda_dlib.cu
  CMake Error at dlib_generated_cuda_dlib.cu.obj.Release.cmake:280 (message):
    Error generating file C:/Users/Vayun
    Mathur/OneDrive/Documents/code/python/dlib/build/temp.win-amd64-3.8/Release/dlib_build/CMakeFiles/dlib.dir/cuda/Release/dlib_generated_cuda_dlib.cu.obj


Traceback (most recent call last):
  File "setup.py", line 223, in <module>
    setup(
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\site-packages\setuptools\command\bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\site-packages\setuptools\command\bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 135, in run
    self.build_extension(ext)
  File "setup.py", line 175, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "C:\Users\Vayun Mathur\anaconda3\envs\AI\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.
```

## Steps to Reproduce

1. Install CUDA 10.2
2. Install cuDNN 7.6.5
3. `git clone https://github.com/davisking/dlib.git`
4. `python setup.py install`

* **Version**:  19.21.99
* **Where did you get dlib**:  This github repo
* **Platform**:  Windows 10 64 bit 10.0.19041 Build 19041
* **Compiler**:  CMake 3.18.2

**Comment by arrufat** [comment]
I am guessing it's (partially?) my fault... It `sqrt_2` in cuda code was added in #2204.

I find it surprising, because the same line uses both `pi` and `sqrt_2`:
https://github.com/davisking/dlib/blob/3ba004f875d02c4c326f8cec5d9ec46b5708ea5a/dlib/cuda/cuda_dlib.cu#L1504

Both defined here:

https://github.com/davisking/dlib/blob/3ba004f875d02c4c326f8cec5d9ec46b5708ea5a/dlib/numeric_constants.h#L9-L10
https://github.com/davisking/dlib/blob/3ba004f875d02c4c326f8cec5d9ec46b5708ea5a/dlib/numeric_constants.h#L15-L16

Maybe it's grabbing `pi` from somewhere else... However, the CI tests passed...

Anyway, can you try with #2210?

**Comment by vayunmathur** [comment]
I tried #2210, and the sqrt_2 issue went away, but the pi issue was still there.

Then I tried to replace pi in the code with a floating point literal, and then it worked.

If I remember right, I think that in CUDA you have to declare variables to be __device__ to use them in a __device__ method?

**Comment by arrufat** [comment]
Thnk you for trying it out. It appears that CUDA already provides the constant I need to use `CUDART_SQRT_2PI`. I've just pushed a fix for that.
