### ISSUE TITLE
cmake missing from setup

### ISSUE THREAD

**Issue by microprediction** [davisking/dlib#2307]
## Expected Behavior

pip install dlib

## Current Behavior
   RuntimeError:
    *******************************************************************
     CMake must be installed to build the following extensions: _dlib_pybind11

## Steps to Reproduce
pip install dlib
Catalina 10.15.6

## Workaround
pip install cmake 
(before pip install dlib)

## Suggested fix
Simply include cmake in setup

**Comment by davisking** [comment]
dlib's setup.py used to depend on cmake but two years ago it was removed because the version of cmake installed on some systems was aggressively broken.  The result was that people would try to install dlib and pip would "install cmake", resulting in a broken cmake being installed, and IIRC hiding a good working cmake user already had.  Resulting in things not working. 

Maybe it's better now.  IDK.  We can try turning it on again and seeing if the pip copy of cmake has its act together now.  I just added the dependency to setup.py.  You can try it and see if it works for you.  Hopefully no one posts an issue where pip broke their cmake installs.

**Comment by microprediction** [comment]
Ah yes, I hope I'm not the bad guy here. Finger's crossed.

**Comment by davisking** [comment]
Na, it's alright.  We will see how it goes :)

**Comment by Hiestaa** [comment]
I just had this issue biting me in my build environment. 

I'm building a project depending on `dlib`, which I compile from source, by cloning this repo. 

Prior to compiling `dlib`, I install `cmake` from ubuntu repos, which get me cmake v3.1.5. This succeeds in compiling `dlib`, and setuptools processes depdencencies without issue:

```
Processing dependencies for dlib==19.21.99
Finished processing dependencies for dlib==19.21.99
```

However, since [this commit](https://github.com/davisking/dlib/commit/8b9d04390ce9545fc4cf3e9d8a981fc71ae8570f) from a couple days ago, setuptools attempts to install cmake v3.18.4 when processing dependencies which doesn't go so well:

```
Processing dependencies for dlib==19.21.99
Searching for cmake
Reading https://pypi.python.org/simple/cmake/
Best match: cmake 3.18.4.post1
Downloading https://files.pythonhosted.org/packages/26/76/b6df98a03343160a27c449c2866d8b94d349be4a3a6632aaf49c8d27916b/cmake-3.18.4.post1.tar.gz#sha256=d7981ac85f1abb75c24eb14936d56dafbd327e7ba371d91007e38704af7b52b5
Processing cmake-3.18.4.post1.tar.gz
Writing /tmp/easy_install-s2_4z0py/cmake-3.18.4.post1/setup.cfg
Running cmake-3.18.4.post1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-s2_4z0py/cmake-3.18.4.post1/egg-dist-tmp-koz6g_67
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-s2_4z0py/cmake-3.18.4.post1/setup.py", line 7, in <module>
    python packages.
ImportError: No module named 'skbuild'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 261, in <module>
    'Topic :: Software Development',
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 414, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 644, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 740, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-s2_4z0py/cmake-3.18.4.post1/setup.py", line 7, in <module>
    python packages.
ImportError: No module named 'skbuild'
Makefile:18: recipe for target 'dlib' failed
make: *** [dlib] Error 1
```

If that can help, this error happened to me while compiling dlib on a docker instance running in AWS codebuild, using an image based off Ubuntu 16.04 and using python 3.5.

**Comment by davisking** [comment]
Ha, here we go with pip's cmake again :)

Ok, so what happens if you make this change?  Does it work?
```
--- a/setup.py
+++ b/setup.py
@@ -233,7 +233,7 @@ setup(
     zip_safe=False,
     # We need an older more-itertools version because v6 broke pytest (for everyone, not just dlib)
     tests_require=['pytest==3.8', 'more-itertools<6.0.0'],
-    install_requires=['cmake'],
+    install_requires=['cmake', 'scikit-build'],
     packages=['dlib'],
     package_dir={'': 'tools/python'},
     keywords=['dlib', 'Computer Vision', 'Machine Learning'],
```
I don't know what business the cmake package has in depending on scikit-build.  The real cmake definitely doesn't depend on that. Anyway, does adding it as a dependency make it work?

**Comment by microprediction** [comment]
Anything I can help test? 

By the way, check out whose the TOP DOG in the Elo ratings now!  1st/61

<img width="340" alt="leaderboard" src="https://user-images.githubusercontent.com/57455669/108451438-d443a180-7234-11eb-9624-470b0e33a97c.png">

**Comment by davisking** [comment]
Sweet. 

What we need is for someone with a system that’s broken by the cmake dependency to check if adding scikit-build as I suggested in the above comment fixes it.

**Comment by Hiestaa** [comment]
Sorry for being a bit slow on the response I only had a chance to give this a test today. This is the result (TL;DR: 👎 the added `install_requires` doesn't solve the problem).

With the following call to `setup`:
```python
setup(
    name='dlib',
    version=read_version_from_cmakelists('dlib/CMakeLists.txt'),
    description='A toolkit for making real world machine learning and data analysis applications',
    long_description='See http://dlib.net for documentation.',
    author='Davis King',
    author_email='davis@dlib.net',
    url='https://github.com/davisking/dlib',
    license='Boost Software License',
    ext_modules=[CMakeExtension('_dlib_pybind11','tools/python')],
    cmdclass=dict(build_ext=CMakeBuild, test=PyTest),
    zip_safe=False,
    # We need an older more-itertools version because v6 broke pytest (for everyone, not just dlib)
    tests_require=['pytest==3.8', 'more-itertools<6.0.0'],
    install_requires=['cmake', 'scikit-build'],
    packages=['dlib'],
    package_dir={'': 'tools/python'},
    keywords=['dlib', 'Computer Vision', 'Machine Learning'],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Science/Research',
        'Intended Audience :: Developers',
        'Operating System :: MacOS :: MacOS X',
        'Operating System :: POSIX',
        'Operating System :: POSIX :: Linux',
        'Operating System :: Microsoft',
        'Operating System :: Microsoft :: Windows',
        'Programming Language :: C++',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.6',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Topic :: Scientific/Engineering',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
        'Topic :: Scientific/Engineering :: Image Recognition',
        'Topic :: Software Development',
    ],
)
```

```
Processing dependencies for dlib==19.21.99
Searching for scikit-build
Reading https://pypi.python.org/simple/scikit-build/
Best match: scikit-build 0.11.1
Downloading https://files.pythonhosted.org/packages/71/02/1e94506b7bee5739317f2d141cebab7dab5bb5731b377e718fddd3b3e7e7/scikit-build-0.11.1.tar.gz#sha256=da40dfd69b2456fad1349a894b90180b43712152b8a85d2a00f4ae2ce8ac9a5c
Processing scikit-build-0.11.1.tar.gz
Writing /tmp/easy_install-l0sermaz/scikit-build-0.11.1/setup.cfg
Running scikit-build-0.11.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-l0sermaz/scikit-build-0.11.1/egg-dist-tmp-j0c5y3hu
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
UPDATING build/lib/skbuild/_version.py
set build/lib/skbuild/_version.py to '0.11.1'
creating /usr/local/lib/python3.5/dist-packages/scikit_build-0.11.1-py3.5.egg
Extracting scikit_build-0.11.1-py3.5.egg to /usr/local/lib/python3.5/dist-packages
Adding scikit-build 0.11.1 to easy-install.pth file

Installed /usr/local/lib/python3.5/dist-packages/scikit_build-0.11.1-py3.5.egg
Searching for cmake
Reading https://pypi.python.org/simple/cmake/
Best match: cmake 3.18.4.post1
Downloading https://files.pythonhosted.org/packages/26/76/b6df98a03343160a27c449c2866d8b94d349be4a3a6632aaf49c8d27916b/cmake-3.18.4.post1.tar.gz#sha256=d7981ac85f1abb75c24eb14936d56dafbd327e7ba371d91007e38704af7b52b5
Processing cmake-3.18.4.post1.tar.gz
Writing /tmp/easy_install-r2w5j87g/cmake-3.18.4.post1/setup.cfg
Running cmake-3.18.4.post1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-r2w5j87g/cmake-3.18.4.post1/egg-dist-tmp-vp6okkux
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-r2w5j87g/cmake-3.18.4.post1/setup.py", line 7, in <module>
    python packages.
ImportError: No module named 'skbuild'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 261, in <module>
    'Topic :: Software Development',
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 414, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 644, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 740, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-r2w5j87g/cmake-3.18.4.post1/setup.py", line 7, in <module>
    python packages.
ImportError: No module named 'skbuild'
Makefile:18: recipe for target 'dlib' failed
make: *** [dlib] Error 1
```

I also tried to specify `skbuild` in `install_requires` (by mistake, not because I wanted to, probably irrelevant) but that didn't help:

```
Processing dependencies for dlib==19.21.99
Searching for skbuild
Reading https://pypi.python.org/simple/skbuild/
Couldn't find index page for 'skbuild' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for skbuild
error: Could not find suitable distribution for Requirement.parse('skbuild')
Makefile:18: recipe for target 'dlib' failed
make: *** [dlib] Error 1
```

**Comment by davisking** [comment]
Alright, I just reverted the change.  So the cmake pip package is back to not being a requirement as far as setup.py is concerned.  It sucks but the cmake pip package is still busted, so we can't use it as an install dependency.

**Comment by SASIN83** [comment]
> Alright, I just reverted the change. So the cmake pip package is back to not being a requirement as far as setup.py is concerned. It sucks but the cmake pip package is still busted, so we can't use it as an install dependency.

So what do I do now if cmake is broken. Previously I tried using some external binaries but now I cant find those either

**Comment by microprediction** [comment]
@SASIN83 I'm guessing you tried upgrading pip and pip install cmake already?

**Comment by SASIN83** [comment]
> @SASIN83 I'm guessing you tried upgrading pip and pip install cmake already?

yes and also tried to install directly from whl file but then it shows not compatible with your system.

**Comment by davisking** [comment]
Uninstall the pip copy of cmake and install the official cmake from cmake.org

**Comment by SASIN83** [comment]
is it okay if I use this 
https://github.com/CodeEZ-Dev/face-recognition_dlib_library and use pre-installed version??
