### ISSUE TITLE
Dlib Linux Web Server Install Error

### ISSUE THREAD

**Issue by hasretja** [davisking/dlib#2332]
Hello,

First of all thank you for this technology.I combined a software I made with Dlib with Flask and turned it into a website.I wanted to share this project with people by putting it in a linux x86_64 host server.But I had a problem installing Dlib. No matter how much I searched, I could not find the solution, I would be glad if you could help.By the way, cmake was downloaded

**When I try the pip install dlib command, I get the following result**

`Collecting dlib
  Using cached dlib-19.21.1.tar.gz (3.6 MB)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-8wni5ums
       cwd: /tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/
  Complete output (65 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.7.8 (default, Aug 11 2020, 06:57:43)
  Invoking CMake setup: 'cmake /tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/build/lib.linux-x86_64-3.7 -DPYTHON_EXECUTABLE=/home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin -DCMAKE_BUILD_TYPE=Release'
  -- The C compiler identification is GNU 4.4.7
  -- The CXX compiler identification is GNU 4.4.7
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin (found version "3.7.8")
  -- Found PythonLibs: /opt/alt/python37/lib64/libpython3.7m.so
  -- Performing Test HAS_CPP14_FLAG
  -- Performing Test HAS_CPP14_FLAG - Failed
  -- Performing Test HAS_CPP11_FLAG
  -- Performing Test HAS_CPP11_FLAG - Failed
  CMake Error at /tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/dlib/external/pybind11/tools/pybind11Tools.cmake:32 (message):
    Unsupported compiler -- pybind11 requires C++11 support!
  Call Stack (most recent call first):
    /tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/dlib/external/pybind11/CMakeLists.txt:33 (include)

  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/setup.py", line 262, in <module>
      'Topic :: Software Development',
    File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/opt/alt/python37/lib64/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/opt/alt/python37/lib64/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/alt/python37/lib64/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/alt/python37/lib64/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/setup.py", line 135, in run
      self.build_extension(ext)
    File "/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/setup.py", line 172, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "/opt/alt/python37/lib64/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE=/home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j5mzdtzi/install-record.txt --single-version-externally-managed --compile --install-headers /home/ury5gska1oii/virtualenv/FaceShape/3.7/include/site/python3.7/dlib
         cwd: /tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/
    Complete output (67 lines):
    running install
    running build
    running build_py
    package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.7.8 (default, Aug 11 2020, 06:57:43)
    Invoking CMake setup: 'cmake /tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/build/lib.linux-x86_64-3.7 -DPYTHON_EXECUTABLE=/home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin -DCMAKE_BUILD_TYPE=Release'
    -- The C compiler identification is GNU 4.4.7
    -- The CXX compiler identification is GNU 4.4.7
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin (found version "3.7.8")
    -- Found PythonLibs: /opt/alt/python37/lib64/libpython3.7m.so
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Failed
    -- Performing Test HAS_CPP11_FLAG
    -- Performing Test HAS_CPP11_FLAG - Failed
    CMake Error at /tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/dlib/external/pybind11/tools/pybind11Tools.cmake:32 (message):
      Unsupported compiler -- pybind11 requires C++11 support!
    Call Stack (most recent call first):
      /tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/dlib/external/pybind11/CMakeLists.txt:33 (include)

    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/setup.py", line 262, in <module>
        'Topic :: Software Development',
      File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/alt/python37/lib64/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/alt/python37/lib64/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/opt/alt/python37/lib64/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/alt/python37/lib64/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/alt/python37/lib64/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/setup.py", line 135, in run
        self.build_extension(ext)
      File "/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/setup.py", line 172, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "/opt/alt/python37/lib64/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE=/home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7tjeokpb/dlib_cc737ae038ee4a50b6ae30a56b51bf38/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j5mzdtzi/install-record.txt --single-version-externally-managed --compile --install-headers /home/ury5gska1oii/virtualenv/FaceShape/3.7/include/site/python3.7/dlib Check the logs for full command output.`

**When I try the python setup.py install --user command I get the following result. I could not reach the document mentioned.**

`running install
Checking .pth file support in /home/ury5gska1oii/.local/lib/python3.7/site-packages/
/home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin -E -c pass
TEST FAILED: /home/ury5gska1oii/.local/lib/python3.7/site-packages/ does NOT support .pth files
bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /home/ury5gska1oii/.local/lib/python3.7/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.
running bdist_egg
running egg_info
writing tools/python/dlib.egg-info/PKG-INFO
writing dependency_links to tools/python/dlib.egg-info/dependency_links.txt
writing top-level names to tools/python/dlib.egg-info/top_level.txt
package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
reading manifest file 'tools/python/dlib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tools/python/build*'
writing manifest file 'tools/python/dlib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Building extension for Python 3.7.8 (default, Aug 11 2020, 06:57:43)
Invoking CMake setup: 'cmake /home/ury5gska1oii/FaceShape/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ury5gska1oii/FaceShape/dlib/build/lib.linux-x86_64-3.7 -DPYTHON_EXECUTABLE=/home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin -DCMAKE_BUILD_TYPE=Release'
CMake Error at /home/ury5gska1oii/FaceShape/dlib/dlib/external/pybind11/tools/pybind11Tools.cmake:32 (message):
  Unsupported compiler -- pybind11 requires C++11 support!
Call Stack (most recent call first):
  /home/ury5gska1oii/FaceShape/dlib/dlib/external/pybind11/CMakeLists.txt:33 (include)

-- Configuring incomplete, errors occurred!
See also "/home/ury5gska1oii/FaceShape/dlib/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/home/ury5gska1oii/FaceShape/dlib/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 261, in <module>
    'Topic :: Software Development',
  File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/alt/python37/lib64/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/alt/python37/lib64/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/opt/alt/python37/lib64/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/alt/python37/lib64/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/opt/alt/python37/lib64/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 134, in run
    self.build_extension(ext)
  File "setup.py", line 171, in build_extension
    subprocess.check_call(cmake_setup, cwd=build_folder)
  File "/opt/alt/python37/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/ury5gska1oii/FaceShape/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ury5gska1oii/FaceShape/dlib/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE=/home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.`

**When I try the python setup.py install --compiler = cygwin command, I get the following result.**

`running build
running build_py
package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
running build_ext
Building extension for Python 3.7.8 (default, Aug 11 2020, 06:57:43)
Invoking CMake setup: 'cmake /home/ury5gska1oii/FaceShape/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ury5gska1oii/FaceShape/dlib/build/lib.linux-x86_64-3.7 -DPYTHON_EXECUTABLE=/home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin -DCMAKE_BUILD_TYPE=Release'
CMake Error at /home/ury5gska1oii/FaceShape/dlib/dlib/external/pybind11/tools/pybind11Tools.cmake:32 (message):
  Unsupported compiler -- pybind11 requires C++11 support!
Call Stack (most recent call first):
  /home/ury5gska1oii/FaceShape/dlib/dlib/external/pybind11/CMakeLists.txt:33 (include)

-- Configuring incomplete, errors occurred!
See also "/home/ury5gska1oii/FaceShape/dlib/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/home/ury5gska1oii/FaceShape/dlib/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 261, in <module>
    'Topic :: Software Development',
  File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/alt/python37/lib64/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/alt/python37/lib64/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/opt/alt/python37/lib64/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 134, in run
    self.build_extension(ext)
  File "setup.py", line 171, in build_extension
    subprocess.check_call(cmake_setup, cwd=build_folder)
  File "/opt/alt/python37/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/ury5gska1oii/FaceShape/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ury5gska1oii/FaceShape/dlib/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE=/home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.`

**When I try the python setup.py install command, I get the following result**

`running install
running bdist_egg
running egg_info
writing tools/python/dlib.egg-info/PKG-INFO
writing dependency_links to tools/python/dlib.egg-info/dependency_links.txt
writing top-level names to tools/python/dlib.egg-info/top_level.txt
package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
reading manifest file 'tools/python/dlib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tools/python/build*'
writing manifest file 'tools/python/dlib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Building extension for Python 3.7.8 (default, Aug 11 2020, 06:57:43)
Invoking CMake setup: 'cmake /home/ury5gska1oii/FaceShape/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ury5gska1oii/FaceShape/dlib/build/lib.linux-x86_64-3.7 -DPYTHON_EXECUTABLE=/home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin -DCMAKE_BUILD_TYPE=Release'
CMake Error at /home/ury5gska1oii/FaceShape/dlib/dlib/external/pybind11/tools/pybind11Tools.cmake:32 (message):
  Unsupported compiler -- pybind11 requires C++11 support!
Call Stack (most recent call first):
  /home/ury5gska1oii/FaceShape/dlib/dlib/external/pybind11/CMakeLists.txt:33 (include)

-- Configuring incomplete, errors occurred!
See also "/home/ury5gska1oii/FaceShape/dlib/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/home/ury5gska1oii/FaceShape/dlib/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 261, in <module>
    'Topic :: Software Development',
  File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/alt/python37/lib64/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/alt/python37/lib64/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/opt/alt/python37/lib64/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ury5gska1oii/virtualenv/FaceShape/3.7/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/alt/python37/lib64/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/opt/alt/python37/lib64/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 134, in run
    self.build_extension(ext)
  File "setup.py", line 171, in build_extension
    subprocess.check_call(cmake_setup, cwd=build_folder)
  File "/opt/alt/python37/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/ury5gska1oii/FaceShape/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ury5gska1oii/FaceShape/dlib/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE=/home/ury5gska1oii/virtualenv/FaceShape/3.7/bin/python3.7_bin', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.`

And I tried many more methods but it didn't work

**Comment by davisking** [comment]
In the text you posted is "Unsupported compiler -- pybind11 requires C++11
support!".   You need a compiler that supports C++11.

**Comment by hasretja** [comment]
Hi Davis,

Thanks for your return.
But the terminal only allows me to use python commands like pip, python setup.py install. Can I install such a c ++ 11 compiler with these methods?

Thanks.

**Comment by hasretja** [comment]
Hello,

First Does not work on Cpanel, you need a VPS machine.And for second problem I solved the problem because of the lack of power of the machine. After copying the code on a better machine, you can install it with python setup.py install.

Thanks.
