### ISSUE TITLE
PyPI source contains `.pyc` files and `__pycache__` directories

### ISSUE THREAD

**Issue by m-roberts** [davisking/dlib#2409]
## Expected Behavior

```
pip3 install stdeb
pypi-download dlib
py2dsc-deb dlib-19.22.0.tar.gz
```
should successfully build `dlib`.

## Current Behavior

```
Traceback (most recent call last):
  File "/home/runner/work/pi-topOS-Upstream-Package-Build/pi-topOS-Upstream-Package-Build/deb_dist/tmp_py2dsc/dlib-19.22.0/setup.py", line 222, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/dist-packages/stdeb/command/sdist_dsc.py", line 125, in run
    raise RuntimeError('original source dist cannot '
RuntimeError: original source dist cannot contain .pyc files
ERROR running: /usr/bin/python3 setup.py --command-packages stdeb.command sdist_dsc --dist-dir=/home/runner/work/pi-topOS-Upstream-Package-Build/pi-topOS-Upstream-Package-Build/deb_dist --use-premade-distfile=/home/runner/work/pi-topOS-Upstream-Package-Build/pi-topOS-Upstream-Package-Build/dlib-19.22.0.tar.gz bdist_deb
ERROR in deb_dist/tmp_py2dsc/dlib-19.22.0
```

Particular note to:
```
RuntimeError: original source dist cannot contain .pyc files
```

**Comment by davisking** [comment]
Heh, oops.  Thanks for reporting this.

**Comment by davisking** [comment]
I just pushed dlib-19.22.1 so this should be all sorted now.

**Comment by m-roberts** [comment]
I can confirm that this is no longer an issue - thanks!

**Comment by davisking** [comment]
Sweet :D
