### ISSUE TITLE
undefined symbol: png_do_expand_palette_rgb8_neon

### ISSUE THREAD

**Issue by BUAADreamer** [davisking/dlib#2524]
When I want to use dlib's python api,I met problem.
What I have done:
ubuntu18.04  
``` shell
installed:libboost-all-dev cmake libx11-dev
python3 setup.py install 
```
And my error is when I use dlib to make predict in python code I met problems:
``` shell
Traceback (most recent call last):
  File "run_server.py", line 14, in <module>
    from util.analysis_server import analysis
  File "/root/engagedetect/util/analysis_server.py", line 5, in <module>
    import dlib
  File "/usr/local/lib/python3.6/dist-packages/dlib-19.23.99-py3.6-linux-aarch64.egg/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: /usr/local/lib/python3.6/dist-packages/dlib-19.23.99-py3.6-linux-aarch64.egg/_dlib_pybind11.cpython-36m-aarch64-linux-gnu.so: undefined symbol: png_do_expand_palette_rgb8_neon
```

**Comment by davisking** [comment]
boost is not needed.

That's not your problem though. There is something wrong with the libpng on your system.  Use `python3 setup.py install --no DLIB_PNG_SUPPORT` to work around it.

**Comment by BUAADreamer** [comment]
> boost is not needed.
> 
> That's not your problem though. There is something wrong with the libpng on your system. Use `python3 setup.py install --no DLIB_PNG_SUPPORT` to work around it.

Thanks,I tried on what you said,but when I compile Python API found problem below.

```
[ 97%] Building CXX object CMakeFiles/_dlib_pybind11.dir/src/image_dataset_metadata.cpp.o
[ 98%] Building CXX object CMakeFiles/_dlib_pybind11.dir/src/numpy_returns.cpp.o
In file included from /root/dlib-master/dlib/../dlib/algs.h:115:0,
                 from /root/dlib-master/dlib/../dlib/serialize.h:218,
                 from /root/dlib-master/dlib/../dlib/python/pybind_utils.h:9,
                 from /root/dlib-master/dlib/../dlib/python.h:6,
                 from /root/dlib-master/tools/python/src/opaque_types.h:6,
                 from /root/dlib-master/tools/python/src/numpy_returns.cpp:1:
/root/dlib-master/dlib/../dlib/data_io/../image_saver/save_png.h: In instantiation of ‘typename dlib::disable_if<dlib::is_matrix<image_type> >::type dlib::save_png(const image_type&, const string&) [with image_type = dlib::numpy_image<dlib::rgb_pixel>; typename dlib::disable_if<dlib::is_matrix<image_type> >::type = void; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/root/dlib-master/tools/python/src/numpy_returns.cpp:51:17:   required from ‘void save_image(dlib::numpy_image<pixel_type>, const string&) [with T = dlib::rgb_pixel; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/root/dlib-master/tools/python/src/numpy_returns.cpp:142:5:   required from here
/root/dlib-master/dlib/../dlib/assert.h:98:45: error: static assertion failed: Failed assertion
     #define COMPILE_TIME_ASSERT(expression) static_assert(expression, "Failed assertion")
                                             ^
/root/dlib-master/dlib/../dlib/data_io/../image_saver/save_png.h:64:13: note: in expansion of macro ‘COMPILE_TIME_ASSERT’
             COMPILE_TIME_ASSERT(sizeof(image_type) == 0);
             ^
/root/dlib-master/dlib/../dlib/data_io/../image_saver/save_png.h: In instantiation of ‘typename dlib::disable_if<dlib::is_matrix<image_type> >::type dlib::save_png(const image_type&, const string&) [with image_type = dlib::numpy_image<unsigned char>; typename dlib::disable_if<dlib::is_matrix<image_type> >::type = void; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/root/dlib-master/tools/python/src/numpy_returns.cpp:51:17:   required from ‘void save_image(dlib::numpy_image<pixel_type>, const string&) [with T = unsigned char; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/root/dlib-master/tools/python/src/numpy_returns.cpp:146:5:   required from here
/root/dlib-master/dlib/../dlib/assert.h:98:45: error: static assertion failed: Failed assertion
     #define COMPILE_TIME_ASSERT(expression) static_assert(expression, "Failed assertion")
                                             ^
/root/dlib-master/dlib/../dlib/data_io/../image_saver/save_png.h:64:13: note: in expansion of macro ‘COMPILE_TIME_ASSERT’
             COMPILE_TIME_ASSERT(sizeof(image_type) == 0);
             ^
CMakeFiles/_dlib_pybind11.dir/build.make:397: recipe for target 'CMakeFiles/_dlib_pybind11.dir/src/numpy_returns.cpp.o' failed
make[2]: *** [CMakeFiles/_dlib_pybind11.dir/src/numpy_returns.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:117: recipe for target 'CMakeFiles/_dlib_pybind11.dir/all' failed
make[1]: *** [CMakeFiles/_dlib_pybind11.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 261, in <module>
    'Topic :: Software Development',
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
    self.build()
  File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 134, in run
    self.build_extension(ext)
  File "setup.py", line 174, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
```
It almost work but also failed.

**Comment by BUAADreamer** [comment]
Solve!!I installed libpng in my server then I can install dlib.Thanks for help!!

**Comment by sandszhouSZ** [comment]
you can alose comment image_saver/save_png.h:64 line to ignore static checking
