### ISSUE TITLE
dlib installation problem for visual studio

### ISSUE THREAD

**Issue by Pankaj9033** [davisking/dlib#2555]
pip install dlib
Collecting dlib
  Using cached dlib-19.23.1.tar.gz (7.4 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      running bdist_wheel
      running build
      running build_py
      package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
      running build_ext
      Building extension for Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
      Invoking CMake setup: 'cmake C:\Users\Pankaj\AppData\Local\Temp\pip-install-h2l0wiyk\dlib_85957971ca0f44d1b7abfc8fd141e675\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Pankaj\AppData\Local\Temp\pip-install-h2l0wiyk\dlib_85957971ca0f44d1b7abfc8fd141e675\build\lib.win-amd64-3.10 -DPYTHON_EXECUTABLE=C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\Pankaj\AppData\Local\Temp\pip-install-h2l0wiyk\dlib_85957971ca0f44d1b7abfc8fd141e675\build\lib.win-amd64-3.10 -A x64'
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:5 (message):

        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

        You must use Visual Studio to build a python extension on windows.  If you
        are getting this error it means you have not installed Visual C++.  Note
        that there are many flavors of Visual Studio, like Visual Studio for C#
        development.  You need to install Visual Studio for C++.

        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Pankaj\AppData\Local\Temp\pip-install-h2l0wiyk\dlib_85957971ca0f44d1b7abfc8fd141e675\setup.py", line 222, in <module>
          setup(
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Pankaj\AppData\Local\Temp\pip-install-h2l0wiyk\dlib_85957971ca0f44d1b7abfc8fd141e675\setup.py", line 134, in run
          self.build_extension(ext)
        File "C:\Users\Pankaj\AppData\Local\Temp\pip-install-h2l0wiyk\dlib_85957971ca0f44d1b7abfc8fd141e675\setup.py", line 171, in build_extension
          subprocess.check_call(cmake_setup, cwd=build_folder)
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Pankaj\\AppData\\Local\\Temp\\pip-install-h2l0wiyk\\dlib_85957971ca0f44d1b7abfc8fd141e675\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Pankaj\\AppData\\Local\\Temp\\pip-install-h2l0wiyk\\dlib_85957971ca0f44d1b7abfc8fd141e675\\build\\lib.win-amd64-3.10', '-DPYTHON_EXECUTABLE=C:\\Users\\Pankaj\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Pankaj\\AppData\\Local\\Temp\\pip-install-h2l0wiyk\\dlib_85957971ca0f44d1b7abfc8fd141e675\\build\\lib.win-amd64-3.10', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
  Running setup.py install for dlib ... error
  error: subprocess-exited-with-error

  × Running setup.py install for dlib did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      running install
      running build
      running build_py
      package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
      running build_ext
      Building extension for Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
      Invoking CMake setup: 'cmake C:\Users\Pankaj\AppData\Local\Temp\pip-install-h2l0wiyk\dlib_85957971ca0f44d1b7abfc8fd141e675\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Pankaj\AppData\Local\Temp\pip-install-h2l0wiyk\dlib_85957971ca0f44d1b7abfc8fd141e675\build\lib.win-amd64-3.10 -DPYTHON_EXECUTABLE=C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\Pankaj\AppData\Local\Temp\pip-install-h2l0wiyk\dlib_85957971ca0f44d1b7abfc8fd141e675\build\lib.win-amd64-3.10 -A x64'
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:5 (message):

        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

        You must use Visual Studio to build a python extension on windows.  If you
        are getting this error it means you have not installed Visual C++.  Note
        that there are many flavors of Visual Studio, like Visual Studio for C#
        development.  You need to install Visual Studio for C++.

        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Pankaj\AppData\Local\Temp\pip-install-h2l0wiyk\dlib_85957971ca0f44d1b7abfc8fd141e675\setup.py", line 222, in <module>
          setup(
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py", line 61, in run
          return orig.install.run(self)
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\command\install.py", line 568, in run
          self.run_command('build')
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Pankaj\AppData\Local\Temp\pip-install-h2l0wiyk\dlib_85957971ca0f44d1b7abfc8fd141e675\setup.py", line 134, in run
          self.build_extension(ext)
        File "C:\Users\Pankaj\AppData\Local\Temp\pip-install-h2l0wiyk\dlib_85957971ca0f44d1b7abfc8fd141e675\setup.py", line 171, in build_extension
          subprocess.check_call(cmake_setup, cwd=build_folder)
        File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Pankaj\\AppData\\Local\\Temp\\pip-install-h2l0wiyk\\dlib_85957971ca0f44d1b7abfc8fd141e675\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Pankaj\\AppData\\Local\\Temp\\pip-install-h2l0wiyk\\dlib_85957971ca0f44d1b7abfc8fd141e675\\build\\lib.win-amd64-3.10', '-DPYTHON_EXECUTABLE=C:\\Users\\Pankaj\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Pankaj\\AppData\\Local\\Temp\\pip-install-h2l0wiyk\\dlib_85957971ca0f44d1b7abfc8fd141e675\\build\\lib.win-amd64-3.10', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dlib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by AhmedElkomey** [comment]
did you find a solution to that?

**Comment by quantum-hash** [comment]
- Download build tools from here https://visualstudio.microsoft.com/visual-cpp-build-tools/.

- Then tick the box : **"Desktop development with C++"** to install CMake, MSVC, Windows 10 SDK..

- And make sure to restart everything or simply your computer.

Hope it helps :)
