### ISSUE TITLE
[Bug]: pip installation

### ISSUE THREAD

**Issue by Niffecs** [davisking/dlib#2801]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

19.24.1

### Python version

3.10

### Compiler

pip

### Expected Behavior

PS C:\Users\Niffecs> pip install dlip
Defaulting to user installation because normal site-packages is not writeable
Collecting dlip
  Using cached dlip-0.0.1-py3-none-any.whl (16 kB)
Collecting pyserial (from dlip)
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting psutil (from dlip)
  Using cached psutil-5.9.5-cp36-abi3-win_amd64.whl (255 kB)
INFO: pip is looking at multiple versions of dlip to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement numnpy (from dlip) (from versions: none)
ERROR: No matching distribution found for numnpy

### Current Behavior

https://pypi.org/project/dlib/

### Steps to Reproduce

https://pypi.org/project/dlib/

### Anything else?

https://pypi.org/project/dlib/

**Comment by Niffecs** [comment]
```powershell
PS C:\Users\Niffecs> pip install dlib --verbose
Using pip 23.1.2 from C:\Users\Niffecs\AppData\Roaming\Python\Python310\site-packages\pip (python 3.10)
Collecting dlib
  Using cached dlib-19.24.1.tar.gz (3.2 MB)
  Running command python setup.py egg_info
  running egg_info
  creating C:\Users\Niffecs\AppData\Local\Temp\pip-pip-egg-info-gb4f95j9\dlib.egg-info
  writing C:\Users\Niffecs\AppData\Local\Temp\pip-pip-egg-info-gb4f95j9\dlib.egg-info\PKG-INFO
  writing dependency_links to C:\Users\Niffecs\AppData\Local\Temp\pip-pip-egg-info-gb4f95j9\dlib.egg-info\dependency_links.txt
  writing top-level names to C:\Users\Niffecs\AppData\Local\Temp\pip-pip-egg-info-gb4f95j9\dlib.egg-info\top_level.txt
  writing manifest file 'C:\Users\Niffecs\AppData\Local\Temp\pip-pip-egg-info-gb4f95j9\dlib.egg-info\SOURCES.txt'
  reading manifest file 'C:\Users\Niffecs\AppData\Local\Temp\pip-pip-egg-info-gb4f95j9\dlib.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'tools\python\build*'
  no previously-included directories found matching 'dlib\cmake_utils\*\build*'
  no previously-included directories found matching 'dlib\test'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  writing manifest file 'C:\Users\Niffecs\AppData\Local\Temp\pip-pip-egg-info-gb4f95j9\dlib.egg-info\SOURCES.txt'
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: dlib
  Running command python setup.py bdist_wheel
  running bdist_wheel
  running build
  running build_py
  running build_ext
  C:\Users\Niffecs\AppData\Local\Temp\pip-install-e3h2minw\dlib_5ffdfb12fc9946cdb612759b5b4d00c3\setup.py:129: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(cmake_version) < '3.1.0':
  Building extension for Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
  Invoking CMake setup: 'cmake C:\Users\Niffecs\AppData\Local\Temp\pip-install-e3h2minw\dlib_5ffdfb12fc9946cdb612759b5b4d00c3\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Niffecs\AppData\Local\Temp\pip-install-e3h2minw\dlib_5ffdfb12fc9946cdb612759b5b4d00c3\build\lib.win-amd64-cpython-310 -DPYTHON_EXECUTABLE=C:\Program Files\Python310\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\Niffecs\AppData\Local\Temp\pip-install-e3h2minw\dlib_5ffdfb12fc9946cdb612759b5b4d00c3\build\lib.win-amd64-cpython-310 -A x64'
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:5 (message):



    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


    You must use Visual Studio to build a python extension on windows.  If you
    are getting this error it means you have not installed Visual C++.  Note
    that there are many flavors of Visual Studio, like Visual Studio for C#
    development.  You need to install Visual Studio for C++.


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!




  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\Niffecs\AppData\Local\Temp\pip-install-e3h2minw\dlib_5ffdfb12fc9946cdb612759b5b4d00c3\setup.py", line 222, in <module>
      setup(
    File "C:\Program Files\Python310\lib\site-packages\setuptools\__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\core.py", line 177, in setup
      return run_commands(dist)
    File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\core.py", line 193, in run_commands
      dist.run_commands()
    File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
      self.run_command(cmd)
    File "C:\Program Files\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
      super().run_command(command)
    File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
      cmd_obj.run()
    File "C:\Program Files\Python310\lib\site-packages\wheel\bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
      super().run_command(command)
    File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
      cmd_obj.run()
    File "C:\Program Files\Python310\lib\site-packages\setuptools\command\build.py", line 24, in run
      super().run()
    File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
      self.run_command(cmd_name)
    File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
      super().run_command(command)
    File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
      cmd_obj.run()
    File "C:\Users\Niffecs\AppData\Local\Temp\pip-install-e3h2minw\dlib_5ffdfb12fc9946cdb612759b5b4d00c3\setup.py", line 134, in run
      self.build_extension(ext)
    File "C:\Users\Niffecs\AppData\Local\Temp\pip-install-e3h2minw\dlib_5ffdfb12fc9946cdb612759b5b4d00c3\setup.py", line 171, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "C:\Program Files\Python310\lib\subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Niffecs\\AppData\\Local\\Temp\\pip-install-e3h2minw\\dlib_5ffdfb12fc9946cdb612759b5b4d00c3\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Niffecs\\AppData\\Local\\Temp\\pip-install-e3h2minw\\dlib_5ffdfb12fc9946cdb612759b5b4d00c3\\build\\lib.win-amd64-cpython-310', '-DPYTHON_EXECUTABLE=C:\\Program Files\\Python310\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Niffecs\\AppData\\Local\\Temp\\pip-install-e3h2minw\\dlib_5ffdfb12fc9946cdb612759b5b4d00c3\\build\\lib.win-amd64-cpython-310', '-A', 'x64']' returned non-zero exit status 1.
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Program Files\Python310\python.exe' -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'C:\\Users\\Niffecs\\AppData\\Local\\Temp\\pip-install-e3h2minw\\dlib_5ffdfb12fc9946cdb612759b5b4d00c3\\setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d 'C:\Users\Niffecs\AppData\Local\Temp\pip-wheel-wsx0vqg8'
  cwd: C:\Users\Niffecs\AppData\Local\Temp\pip-install-e3h2minw\dlib_5ffdfb12fc9946cdb612759b5b4d00c3\
  Building wheel for dlib (setup.py) ... error
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
  Running command python setup.py clean
  running clean
  removing 'build\temp.win-amd64-cpython-310' (and everything under it)
  'build\lib.win-amd64-cpython-310' does not exist -- can't clean it
  'build\bdist.win-amd64' does not exist -- can't clean it
  'build\scripts-3.10' does not exist -- can't clean it
  removing 'build'
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects
PS C:\Users\Niffecs>
```

**Comment by goyalyashpal** [comment]
i am facing same issue, why was this closed?? 

[xkcd: Wisdom of the Ancients](https://xkcd.com/979/)

![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)
