### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by KrishnChauhan** [davisking/dlib#2845]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

not installed yet ue to error

### Python version

3.8

### Compiler

 GCC 4.8.5 20150623 

### Expected Behavior

wanted to install requirement.txt for FaceREcognition project which has the following dependencies -- flask
dlib
face_recognition
pillow
imutils
numpy
opencv-python
h5py
scikit-learn
...

### Current Behavior

Could not build wheen for dlib which is required to install pyoproject.toml-based project.

### Steps to Reproduce

sudo yum install -r requirement.txt. And i already had installed cmake and other dependecies after upgrading pip  and yum.

**Comment by KrishnChauhan** [comment]
[root@localhost AMSAPI]# pip install dlib
 4.8.5 20150623 Collecting dlib
  Using cached dlib-19.24.2.tar.gz (11.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: dlib
  Building wheel for dlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for dlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [91 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Building extension for Python 3.8.12 (default, Aug  4 2023, 19:09:54)
      Invoking CMake setup: 'cmake /tmp/pip-install-82p84j4m/dlib_a11b96784ea344989671b2bbd02dd06a/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-82p84j4m/dlib_a11b96784ea344989671b2bbd02dd06a/build/lib.linux-x86_64-cpython-38 -DPYTHON_EXECUTABLE=/usr/local/bin/python3.8 -DCMAKE_BUILD_TYPE=Release'
      -- The C compiler identification is unknown
      -- The CXX compiler identification is GNU 4.8.5
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: /usr/bin/g++
      -- Check for working C compiler: /usr/bin/g++ - broken
      CMake Error at /tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler

          "/usr/bin/g++"

        is not able to compile a simple test program.

        It fails with the following output:

          Change Dir: '/tmp/pip-install-82p84j4m/dlib_a11b96784ea344989671b2bbd02dd06a/build/temp.linux-x86_64-cpython-38/CMakeFiles/CMakeScratch/TryCompile-1kc0cz'

          Run Build Command(s): /tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/cmake/data/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_0da95/fast
          /usr/bin/gmake  -f CMakeFiles/cmTC_0da95.dir/build.make CMakeFiles/cmTC_0da95.dir/build
          gmake[1]: Entering directory `/tmp/pip-install-82p84j4m/dlib_a11b96784ea344989671b2bbd02dd06a/build/temp.linux-x86_64-cpython-38/CMakeFiles/CMakeScratch/TryCompile-1kc0cz'
          Building C object CMakeFiles/cmTC_0da95.dir/testCCompiler.c.o
          /usr/bin/g++    -o CMakeFiles/cmTC_0da95.dir/testCCompiler.c.o -c /tmp/pip-install-82p84j4m/dlib_a11b96784ea344989671b2bbd02dd06a/build/temp.linux-x86_64-cpython-38/CMakeFiles/CMakeScratch/TryCompile-1kc0cz/testCCompiler.c
          /tmp/pip-install-82p84j4m/dlib_a11b96784ea344989671b2bbd02dd06a/build/temp.linux-x86_64-cpython-38/CMakeFiles/CMakeScratch/TryCompile-1kc0cz/testCCompiler.c:2:3: error: #error "The CMAKE_C_COMPILER is set to a C++ compiler"
           # error "The CMAKE_C_COMPILER is set to a C++ compiler"
             ^
          gmake[1]: *** [CMakeFiles/cmTC_0da95.dir/testCCompiler.c.o] Error 1
          gmake[1]: Leaving directory `/tmp/pip-install-82p84j4m/dlib_a11b96784ea344989671b2bbd02dd06a/build/temp.linux-x86_64-cpython-38/CMakeFiles/CMakeScratch/TryCompile-1kc0cz'
          gmake: *** [cmTC_0da95/fast] Error 2





        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:14 (project)


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 218, in <module>
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 346, in run
          self.run_command("build")
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-x93xanpf/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 130, in run
        File "<string>", line 167, in build_extension
        File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-82p84j4m/dlib_a11b96784ea344989671b2bbd02dd06a/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-82p84j4m/dlib_a11b96784ea344989671b2bbd02dd06a/build/lib.linux-x86_64-cpython-38', '-DPYTHON_EXECUTABLE=/usr/local/bin/python3.8', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects

**Comment by arrufat** [comment]
GCC 4.8 is no longer supported.
