### ISSUE TITLE
[Bug]: CUDA 11.8 & CUDNN 8 ISSUE | ImportError: DLL load failed while importing _dlib_pybind11: The specified module could not be found

### ISSUE THREAD

**Issue by EKI-INDRADI** [davisking/dlib#2884]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

19.24.2 (pip) & 19.24.4  (using github)

### Python version

3,8 & 3.9

### Compiler

CMake (latest)

### Expected Behavior

how to fix  it

### Current Behavior

help im tired 3 days not solved, how t o fix
run using anaconda3

[ERROR  DETAIL](https://github.com/OpenTalker/video-retalking/issues/133)

```sh
conda activate video_retalking

(video_retalking) V:\_video_retalking\video-retalking>python inference.py --face "examples/face/1.mp4" --audio "examples/audio/1.wav" --outfile "results/1_1.mp4"
V:\_video_retalking\video-retalking\third_part/GPEN\align_faces.py:251: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if align_type is 'cv2_affine':
V:\_video_retalking\video-retalking\third_part/GPEN\align_faces.py:254: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif align_type is 'cv2_rigid':
V:\_video_retalking\video-retalking\third_part/GPEN\align_faces.py:257: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif align_type is 'affine':
Traceback (most recent call last):
  File "V:\_video_retalking\video-retalking\inference.py", line 22, in <module>
    from utils.ffhq_preprocess import Croper
  File "V:\_video_retalking\video-retalking\utils\ffhq_preprocess.py", line 31, in <module>
    import dlib
  File "D:\__________________INSTALL\ANACONDA\envs\video_retalking\lib\site-packages\dlib\__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed while importing _dlib_pybind11: The specified module could not be found.
```

dlib_init.py

```py
# Copyright (C) 2020  Davis E. King (davis@dlib.net)
# License: Boost Software License   See LICENSE.txt for the full license.

def add_lib_to_dll_path(path):
    """ On windows you must call os.add_dll_directory() to allow linking to external DLLs.  See
    https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew.  This function adds the folder
    containing path to the dll search path. 
    """
    try:
        import os
        os.add_dll_directory(os.path.join(os.path.dirname(path), '../../bin'))
    except (AttributeError,KeyError,FileNotFoundError):
        pass

if 'OFF' == 'ON':
    add_lib_to_dll_path('C:/CUDA_11_CUDDN_8/lib/x64/cudnn.lib')
    add_lib_to_dll_path('C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/lib/x64/cudart.lib')

from _dlib_pybind11 import *
from _dlib_pybind11 import __version__, __time_compiled__
```

```sh
(video_retalking) V:\_video_retalking\video-retalking>python
Python 3.9.18 (main, Sep 11 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\__________________INSTALL\ANACONDA\envs\video_retalking\lib\site-packages\dlib\__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed while importing _dlib_pybind11: The specified module could not be found.
>>> dlib.DLIB_USE_CUDA
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'dlib' is not defined
>>> quit()
```

### Steps to Reproduce

[STEP](https://github.com/OpenTalker/video-retalking)

**Comment by maazalam530** [comment]
Facing same issue!!! Literally tired of searching

**Comment by EKI-INDRADI** [comment]
solution for windows : https://github.com/EKI-INDRADI/video-retalking-tested-20231020/tree/main

install anaconda & cmake (windows) https://cmake.org/download/

```sh
cmake --version
git clone https://github.com/natlamir/video-retalking.git
cd video-retalking
rename natlamir-video-retalking
conda create -n natlamir_video_retalking python=3.8
conda activate natlamir_video_retalking

conda install ffmpeg
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

pip install -r requirements.txt
```

solved

**Comment by maazalam530** [comment]
It worked. Thank You soo much.
