### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Jeevitha-2005** [davisking/dlib#2886]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

not installed

### Python version

3.12

### Compiler

vs code

### Expected Behavior

dlib installed successfully

### Current Behavior

PS C:\Users\JEEVITHA S> pip install dlib
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\JEEVITHA S\AppData\Local\Programs\Python\Python312\Scripts\pip.exe\__main__.py", line 4, in <module>
  File "C:\Users\JEEVITHA S\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\JEEVITHA S\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\JEEVITHA S\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\cli\main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "C:\Users\JEEVITHA S\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\cli\cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "C:\Users\JEEVITHA S\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\cli\parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "C:\Users\JEEVITHA S\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\configuration.py", line 20, in <module>
    from pip._internal.exceptions import (
  File "C:\Users\JEEVITHA S\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\exceptions.py", line 7, in <module>
    from pip._vendor.pkg_resources import Distribution
  File "C:\Users\JEEVITHA S\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2164, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

### Steps to Reproduce

i have every necessary libraries
python version 3.12
pip version 23.3.1

**Comment by davisking** [comment]
That `'pkgutil' has no attribute 'ImpImporter'` is happening inside some other package unrelated to dlib.  So I don't know what the problem is.  Maybe your python distribution is messed up somehow :shrug:
