### ISSUE TITLE
[Bug]: ERROR Backend subprocess exited when trying to invoke build_wheel

### ISSUE THREAD

**Issue by mr-lunart** [davisking/dlib#2894]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

19.24

### Python version

3.11

### Compiler

C++ compiler

### Expected Behavior

No respone

### Current Behavior

i get this error when build dlib both from pip and from github

```
Building extension for Python 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)]
Invoking CMake setup: 'cmake /home/neoma/Bangkit/flask/dlib-19.24.2/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/neoma/Bangkit/flask/dlib-19.24.2/build/lib.linux-x86_64-cpython-311 -DPYTHON_EXECUTABLE=/tmp/build-env-l0wjojro/bin/python -DCMAKE_BUILD_TYPE=Release'
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:14 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/home/neoma/Bangkit/flask/.venv/lib64/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/home/neoma/Bangkit/flask/.venv/lib64/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neoma/Bangkit/flask/.venv/lib64/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/build_meta.py", line 404, in build_wheel
    return self._build_with_temp_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
    self.run_setup()
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
    super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 222, in <module>
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/wheel/bdist_wheel.py", line 369, in run
    self.run_command("build")
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/tmp/build-env-l0wjojro/lib64/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "<string>", line 134, in run
  File "<string>", line 171, in build_extension
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/neoma/Bangkit/flask/dlib-19.24.2/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/neoma/Bangkit/flask/dlib-19.24.2/build/lib.linux-x86_64-cpython-311', '-DPYTHON_EXECUTABLE=/tmp/build-env-l0wjojro/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

ERROR Backend subprocess exited when trying to invoke build_wheel
```

### Steps to Reproduce

it happen everytime i install dlib

### Anything else?

is there any way that can solve this?

**Comment by mr-lunart** [comment]
the issue get resolve after installing some package.
fedora
`sudo dnf install make automake gcc gcc-c++ kernel-devel`
ubuntu
`sudo apt-get update && sudo apt-get install build-essential`
