### ISSUE TITLE
[Bug]: PHP crashed with dlib and pdlib

### ISSUE THREAD

**Issue by SoreMole** [davisking/dlib#3007]
### What Operating System(s) are you seeing this problem on?

Other (plase, specify in the Steps to Reproduce)

### dlib version

git version

### Python version

3.11

### Compiler

gcc 14

### Expected Behavior

I'm try to include PHP pdlib module with dlib library in nextcloud php-fpm instance, so i could test image recognize functions.

### Current Behavior

PHP-fpm crashed with signal 6, or signal 11. So i turn on all debug properties and modules and try to start gdb with php. PHP crashes at __atexit function with no location.

### Steps to Reproduce

FreeBSD 14, gcc14 compiled php and dlib.
gdb php
Reading symbols from php...
(gdb) b __cxa_atexit
Function "__cxa_atexit" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (__cxa_atexit) pending.
(gdb) b cleanup_ps_args
Breakpoint 2 at 0x9164b3: file /usr/ports/lang/php83/work/php-8.3.11/sapi/cli/ps_title.c, line 438.
(gdb) r
Starting program: /usr/local/bin/php

Breakpoint 1, __cxa_atexit (func=0x801e3a030 <std::__1::DoIOSInit::~DoIOSInit()>, arg=0x801e89a60,
    dso=0x801e84150 <__dso_handle>) at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb) c
Continuing.

Breakpoint 1, __cxa_atexit (func=0x801e3a0e0 <std::__1::ios_base::Init::~Init()>,
    arg=0x801e89508 <std::__1::__start_std_streams>, dso=0x801e84150 <__dso_handle>)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x802ec6fd0 <std::ios_base::Init::~Init()>, arg=0x8030735f0, dso=0x803072060)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x802eaeac0, arg=0x803072310, dso=0x803072060)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x802eaea80, arg=0x803072308, dso=0x803072060)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x802ee0210, arg=0x803072208, dso=0x803072060)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x802ee1850, arg=0x803072220, dso=0x803072060)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x802ee6110, arg=0x803072240, dso=0x803072060)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x802ee6120, arg=0x803072238, dso=0x803072060)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x802faa190, arg=0x803072290, dso=0x803072060)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x802faa1a0, arg=0x803072288, dso=0x803072060)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x802faa1b0, arg=0x803072280, dso=0x803072060)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x802fc8dd0, arg=0x8030763c0, dso=0x803072060)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x80e62a6f0 <x265::Lock::~Lock()>, arg=0x80f761480 <x265::BitCost::s_costCalcLock>,
    dso=0x80f75eec0) at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766a60 <SeiMetadataDictionary::JsonDataKeys::LocalParameters>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766a78 <SeiMetadataDictionary::JsonDataKeys::TargetDisplayLuminance>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766a90 <SeiMetadataDictionary::JsonDataKeys::NumberOfWindows>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766aa8 <SeiMetadataDictionary::BezierCurveNames::TagName>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766ac0 <SeiMetadataDictionary::BezierCurveNames::NumberOfAnchors>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766ad8 <SeiMetadataDictionary::BezierCurveNames::KneePointX>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766af0 <SeiMetadataDictionary::BezierCurveNames::KneePointY>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766b08 <SeiMetadataDictionary::BezierCurveNames::AnchorsTag>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x80eb28ec0, arg=0x0, dso=0x80f75eec0) at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766c70 <SeiMetadataDictionary::EllipseSelectionNames::WindowUpperLeftCornerX>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766c88 <SeiMetadataDictionary::EllipseSelectionNames::WindowUpperLeftCornerY>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766ca0 <SeiMetadataDictionary::EllipseSelectionNames::WindowLowerRightCornerX>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766cb8 <SeiMetadataDictionary::EllipseSelectionNames::WindowLowerRightCornerY>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766cd0 <SeiMetadataDictionary::EllipseSelectionNames::WindowData>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766ce8 <SeiMetadataDictionary::EllipseNames::TagName>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766d00 <SeiMetadataDictionary::EllipseNames::RotationAngle>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766d18 <SeiMetadataDictionary::EllipseNames::CenterOfEllipseX>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766d30 <SeiMetadataDictionary::EllipseNames::CenterOfEllipseY>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766d48 <SeiMetadataDictionary::EllipseNames::OverlapProcessOption>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766d60 <SeiMetadataDictionary::EllipseNames::SemiMajorAxisExternalEllipse>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766d78 <SeiMetadataDictionary::EllipseNames::SemiMinorAxisExternalEllipse>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766d90 <SeiMetadataDictionary::EllipseNames::SemiMajorAxisInternalEllipse>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766da8 <SeiMetadataDictionary::PercentileNames::TagName>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766dc0 <SeiMetadataDictionary::PercentileNames::NumberOfPercentiles>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766dd8 <SeiMetadataDictionary::PercentileNames::DistributionIndex>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f766df0 <SeiMetadataDictionary::PercentileNames::DistributionValues>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x80eb290c0, arg=0x0, dso=0x80f75eec0) at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x80eb292e0, arg=0x0, dso=0x80f75eec0) at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f7670e8 <SeiMetadataDictionary::LuminanceNames::TagName>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f767100 <SeiMetadataDictionary::LuminanceNames::LlcTagName>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f767118 <SeiMetadataDictionary::LuminanceNames::AverageRGB>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f767130 <SeiMetadataDictionary::LuminanceNames::MaxSCL>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f767148 <SeiMetadataDictionary::LuminanceNames::MaxSCL0>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f767160 <SeiMetadataDictionary::LuminanceNames::MaxSCL1>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (
    func=0x801e71770 <std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()>, arg=0x80f767178 <SeiMetadataDictionary::LuminanceNames::MaxSCL2>, dso=0x80f75eec0)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x80eb85f60 <x265_10bit::Lock::~Lock()>,
    arg=0x80f767780 <x265_10bit::BitCost::s_costCalcLock>, dso=0x80f75eec0) at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x80f1a67d0 <x265_12bit::Lock::~Lock()>,
    arg=0x80f76cf90 <x265_12bit::BitCost::s_costCalcLock>, dso=0x80f75eec0) at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x801e6cb30 <std::__1::mutex::~mutex()>, arg=0x80cd7b020, dso=0x80cd73450)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x808155e20 <dlib::logger::~logger()>,
    arg=0x80835e6e0 <dlib::logger_helper_stuff::log>, dso=0x80835d8d8) at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x80816dbf0 <dlib::mutex::~mutex()>,
    arg=0x80835eb78 <dlib::connect_timeout_helpers::connect_mutex>, dso=0x80835d8d8)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x80817a700 <dlib::signaler::~signaler()>,
    arg=0x80835eb60 <dlib::connect_timeout_helpers::connect_signaler>, dso=0x80835d8d8)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x80816dbf0 <dlib::mutex::~mutex()>,
    arg=0x80835eb98 <dlib::sockets_kernel_2_mutex::startup_lock>, dso=0x80835d8d8)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x808155e20 <dlib::logger::~logger()>, arg=0x80835ebc0 <dlib::server::sdlog>,
    dso=0x80835d8d8) at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x808155e20 <dlib::logger::~logger()>,
    arg=0x80835ee80 <dlib::server_iostream::_dLog>, dso=0x80835d8d8) at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x808155e20 <dlib::logger::~logger()>, arg=0x80835f140 <dlib::server_http::dlog>,
    dso=0x80835d8d8) at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x8081a2dc0 <std::shared_ptr<dlib::timer_global_clock>::~shared_ptr()>,
    arg=0x80835f480 <dlib::get_global_clock()::d>, dso=0x80835d8d8) at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x80822cab0 <std::function<bool (double)>::~function()>,
    arg=0x80835f520 <dlib::never_stop_early>, dso=0x80835d8d8) at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x80822cab0 <std::function<bool (double)>::~function()>,
    arg=0x80835f560 <dlib::never_stop_early>, dso=0x80835d8d8) at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 1, __cxa_atexit (func=0x8082d8310 <std::shared_ptr<dlib::mutex>::~shared_ptr()>,
    arg=0x80835f660 <dlib::gui_core_kernel_2_globals::global_mutex()::m>, dso=0x80835d8d8)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.
^D
Breakpoint 1, __cxa_atexit (
    func=0x808199470 <dlib::threads_kernel_shared::threader_destruct_helper::~threader_destruct_helper()>,
    arg=0x80835f3f8 <dlib::threads_kernel_shared::thread_pool()::a>, dso=0x80835d8d8)
    at /usr/src/lib/libc/stdlib/atexit.c:179
179             fn.fn_type = ATEXIT_FN_CXA;
(gdb)
Continuing.

Breakpoint 2, cleanup_ps_args (argv=0x7fffffffe9a8) at /usr/ports/lang/php83/work/php-8.3.11/sapi/cli/ps_title.c:438
438         if (save_argv)
(gdb) s
440             save_argv = NULL;
(gdb)
441             save_argc = 0;
(gdb)
467         return;
(gdb)
468     }
(gdb)
main (argc=1, argv=0x7fffffffe9a8) at /usr/ports/lang/php83/work/php-8.3.11/sapi/cli/php_cli.c:1376
1376            exit(exit_status);
(gdb)
exit (status=0) at /usr/src/lib/libc/stdlib/exit.c:63
63              _thread_autoinit_dummy_decl = 1;
(gdb)
70              __cxa_thread_call_dtors();
(gdb)
__cxa_thread_call_dtors () at /usr/src/lib/libc/stdlib/cxa_thread_atexit_impl.c:141
141             for (i = 0; i < CXA_DTORS_ITERATIONS && !LIST_EMPTY(&dtors); i++)
(gdb)
151     }
(gdb)
exit (status=0) at /usr/src/lib/libc/stdlib/exit.c:71
71              __cxa_finalize(NULL);
(gdb)
__cxa_finalize (dso=dso@entry=0x0) at /usr/src/lib/libc/stdlib/atexit.c:206
206             if (dso != NULL) {
(gdb)
210                     global_exit = 1;
(gdb)
213             _MUTEX_LOCK(&atexit_mutex);
(gdb)
214             for (p = __atexit; p; p = p->next) {
(gdb)
215                     for (n = p->ind; --n >= 0;) {
(gdb)
216                             if (p->fns[n].fn_type == ATEXIT_FN_EMPTY)
(gdb)
218                             fn = p->fns[n];
(gdb)
206             if (dso != NULL) {
(gdb)
219                             if (dso != NULL && dso != fn.fn_dso) {
(gdb)
230                             p->fns[n].fn_type = ATEXIT_FN_EMPTY;
(gdb)
231                             _MUTEX_UNLOCK(&atexit_mutex);
(gdb)
234                             if (fn.fn_type == ATEXIT_FN_CXA)
(gdb)
235                                     fn.fn_ptr.cxa_func(fn.fn_arg);
(gdb)

Program received signal SIGSEGV, Segmentation fault.
Address not mapped to object.
0x0000000808199470 in ?? ()
(gdb) bt
#0  0x0000000808199470 in ?? ()
#1  0x0000000801522dff in __cxa_finalize (dso=dso@entry=0x0) at /usr/src/lib/libc/stdlib/atexit.c:235
#2  0x0000000801523331 in exit (status=0) at /usr/src/lib/libc/stdlib/exit.c:71
#3  0x000000000090c25d in main (argc=1, argv=0x7fffffffe9a8)

### Anything else?

As far as i could understand - something in dlib register some mutex, or something else which unregister twice?

**Comment by SoreMole** [comment]
Is it possible somehow to hunt down this issue?
