### ISSUE TITLE
Can't convert 'NoneType' object to str implicitly

### ISSUE THREAD

**Issue by PhanDuc** [davisking/dlib#399]
I installed cmake then tried run : python setup.py install 
But i had this error : 
```
running install
running bdist_egg
running build
Detected Python architecture: 64bit
Traceback (most recent call last):
  File "setup.py", line 650, in <module>
    'Topic :: Software Development',
  File "C:\Python34\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 596, in run
    self.run_command("build")
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 405, in run
    self.build_dlib()
  File "setup.py", line 511, in build_dlib
    cmake_extra_arch += ['-DPYTHON_LIBRARY=' + sysconfig.get_config_var('LIBDIR')]
TypeError: Can't convert 'NoneType' object to str implicitly
```
How to fix this problem and make successful install dblib ?
Thanks so much !

**Comment by davisking** [comment]
Try the latest code in github.

**Comment by PhanDuc** [comment]
I downloaded the latest code from github but still error !

**Comment by davisking** [comment]
I updated the code a few hours ago to fix this.  DId you get the code since then?

**Comment by PhanDuc** [comment]
Hi, i got the code and ran but i had another error : 
```

E:\Portable\dlib-master_2\dlib-master>python setup.py install
running install
running bdist_egg
running build
Detected Python architecture: 64bit
Detected platform: win32
Removing build directory E:\Portable\dlib-master_2\dlib-master\./tools/python/build
Configuring cmake ...
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error in CMakeLists.txt:
  No CMAKE_C_COMPILER could be found.
CMake Error in CMakeLists.txt:
  No CMAKE_CXX_COMPILER could be found.
-- Configuring incomplete, errors occurred!
See also "E:/Portable/dlib-master_2/dlib-master/tools/python/build/CMakeFiles/CMakeOutput.log".
See also "E:/Portable/dlib-master_2/dlib-master/tools/python/build/CMakeFiles/CMakeError.log".
error: cmake configuration failed!
```
I installed CMake and added to Path but still error.

**Comment by PhanDuc** [comment]
Yes, i downloaded and ran, but now i tried to configuration with cmake

```
Configuring cmake ...
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1518 (message):
  No header defined for python-py34; skipping header check
Call Stack (most recent call first):
  E:/Portable/dlib-master_2/dlib-master/dlib/cmake_utils/add_python_module:61 (FIND_PACKAGE)
  CMakeLists.txt:6 (include)
-- Could NOT find Boost
CMake Warning at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1518 (message):
  No header defined for python-py35; skipping header check
Call Stack (most recent call first):
  E:/Portable/dlib-master_2/dlib-master/dlib/cmake_utils/add_python_module:63 (FIND_PACKAGE)
  CMakeLists.txt:6 (include)
-- Could NOT find Boost
CMake Warning at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1518 (message):
  No header defined for python3; skipping header check
Call Stack (most recent call first):
  E:/Portable/dlib-master_2/dlib-master/dlib/cmake_utils/add_python_module:66 (FIND_PACKAGE)
  CMakeLists.txt:6 (include)
-- Could NOT find Boost
-- Could NOT find Boost
-- Found PythonLibs: C:/Python34/libs/python34.lib (found suitable version "3.4.3", minimum required is "3.4")
--  *****************************************************************************************************
-- We couldn't find the right version of boost python.  If you installed boost and you are still getting this error then you might have installed a version of boost that was compiled with a different version of visual studio than the one you are using.  So you have to make sure that the version of visual studio is the same version that was used to compile the copy of boost you are using.
--  Set the BOOST_ROOT and BOOST_LIBRARYDIR environment variables before running cmake.
--  E.g.  Something like this:
--     set BOOST_ROOT=C:\local\boost_1_57_0
--     set BOOST_LIBRARYDIR=C:\local\boost_1_57_0\stage\lib
--
--  You will also likely need to compile boost yourself rather than using one of the precompiled
--  windows binaries.  Do this by going to the folder tools\build\ within boost and running
--  bootstrap.bat.  Then run the command:
--     b2 install
--  And then add the output bin folder to your PATH.  Usually this is the C:\boost-build-engine\bin
--  folder. Finally, go to the boost root and run a command like this:
--     b2 -a --with-python address-model=64 toolset=msvc runtime-link=static
--  When it completes, set BOOST_LIBRARYDIR equal to wherever b2 put the compiled libraries.
error: cmake configuration failed!
```

**Comment by davisking** [comment]
That huge message you pasted in litterally tells you what to do.
