### ISSUE TITLE
I have issues in "python setup.py build"

### ISSUE THREAD

**Issue by wangyarui** [davisking/dlib#533]
I have cmake build successfully,but when I run python setup.py build,I have met with the following issues,wish to get your reply,thanks!(I have ever make it successfully):

Traceback (most recent call last):
  File "setup.py", line 397, in <module>
    clean_dist()
  File "setup.py", line 387, in clean_dist
    rmtree(dist_dir)
  File "setup.py", line 371, in rmtree
    shutil.rmtree(name, ignore_errors=False, onerror=remove_read_only)
  File "/home/richal/miniconda2/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "setup.py", line 367, in remove_read_only
    os.chmod(path, stat.S_IRWXU | stat.S_IRWXG | stat.S_IRWXO)
OSError: [Errno 1] Operation not permitted: '/home/richal/software/dlib/./dist/dlib-19.3.99-py2.7-linux-x86_64.egg'

**Comment by davisking** [comment]
It's saying you don't have write permissions to your hard drive.  That's not a dlib related error.
