### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 14

### ISSUE THREAD

**Issue by programes** [davisking/dlib#609]
Traceback (most recent call last):
  File "setup.py", line 649, in <module>
    'Topic :: Software Development',
  File "D:\Language\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Language\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Language\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Language\Python36\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\Language\Python36\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Language\Python36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Language\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 595, in run
    self.run_command("build")
  File "D:\Language\Python36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Language\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 406, in run
    self.build_dlib()
  File "setup.py", line 571, in build_dlib
    if run_process(cmake_cmd):
  File "setup.py", line 304, in run_process
    _log_buf(buf)
  File "setup.py", line 272, in _log_buf
    buf = buf.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 14: invalid continuation byte

**Comment by davisking** [comment]
Post the instructions necessary to reproduce this error.
