### ISSUE TITLE
ImportError undefined symbol: _ZTINSt6thread6_StateE

### ISSUE THREAD

**Issue by pkjai** [davisking/dlib#807]
Hi, I recently tried to install dlib on ubuntu 16.04 and came across an error. I am using anaconda and python2.
```
sudo apt-get install build-essential cmake pkg-config
sudo apt-get install libx11-dev libatlas-base-dev
sudo apt-get install libgtk-3-dev libboost-python-dev
source activate dev2
pip install dlib
```
The installation seemed to work fine but then I got this error when I tried to import dlib in python.
```
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda2/envs/dev2/lib/python2.7/site-packages/dlib-19.6.0-py2.7-linux-x86_64.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: /home/ubuntu/anaconda2/envs/dev2/lib/python2.7/site-packages/dlib-19.6.0-py2.7-linux-x86_64.egg/dlib/dlib.so: undefined symbol: _ZTINSt6thread6_StateE
```
Please advise.

**Comment by pkjai** [comment]
I was using gcc-6. Everything works when after I switched to gcc-5.
